### ISSUE TITLE
OpenGraphContent on swift3

### ISSUE THREAD

**Issue by GabrieleCicconetti** [facebook/facebook-sdk-swift#105]
let object: OpenGraphObject = [
            "og:type": "books.book",
            "og:title": "A Game of Thrones",
            "og:description": "In the frozen wastes to the north of Winterfell, sinister and supernatural forces are mustering.",
            "books:isbn": "0-553-57340-3"
        ]
        // Create an action
        var action = OpenGraphAction(type: "book.reads")
        action["books:book"] = object
        // Create the content
        var content = OpenGraphShareContent()
        content.action = action
        content.previewPropertyName = "books:book"
        try ShareDialog.show(from: self, content: content) //Here i'm getting "generic parameter 'Content' could not be inferred" 

what i'm doing wrong??

**Comment by hhartz** [comment]
@GabrieleCicconetti I'm having the same issue - did you manage to resolve this?

**Comment by marcway** [comment]
I also have the same issue. Anyone could solve this?

**Comment by hhartz** [comment]
@GabrieleCicconetti @marcway actually, it seems this module is no longer maintained. If you use CocoaPods, and `use_frameworks!`, adding `pod 'FBSDKShareKit'` and `import FBSDKShareKit` lets you do this using `FBSDKShareOpenGraphObject`, `FBSDKShareOpenGraphAction`, `FBSDKShareOpenGraphContent` and `FBSDKShareDialog`

**Comment by RPCarter53** [comment]
This issue can be worked around with the following simple extension. The association to the ContentProtocol is missing in the original source.

extension OpenGraphShareContent : ContentProtocol {
    }

Beyond this however other problems will arise due to a faulty initiator for OpenGraphPropertyName. The initiator with suggested corrections is..

  public init?(_ string: String) {
    // let components = string.characters.split(separator: ":")
    let components = string.characters.split(separator: ":", maxSplits: 1) // suggested alternative
    guard components.count >= 2 else {
      return nil
    }

    self.namespace = String(components[0])
    self.name = String(components[1])   // suggested alternaive

    // The following original gives array index out of range and an invalid build of name
    //let subcharacters = components[1 ... components.count]
    //self.name = subcharacters.reduce("", { $0 + ":" + String($1) })
  }

**Comment by VikasPrajapati27** [comment]
Still, an issue is not solved.
