### ISSUE TITLE
Carthage hanging on cloning/fetching

### ISSUE THREAD

**Issue by adrianodiasx93** [facebook/facebook-sdk-swift#107]
When I try `carthage update --platform iOS` it hangs on cloning/fetching "facebook-ios-sdk" which is cloned because of facebook-sdk-swift carthage's file. 

It takes hours and then starts fetching Bolts-ObjC (cloned because of facebook-ios-sdk) multiple times.

Both repositories have been updated. Any chance either update has caused the issue? Could you please check it? 

Appreciate it.

**Comment by LingoLasse** [comment]
I have the same problem.

**Comment by adrianodiasx93** [comment]
I solved the issue after specifying the versions of some of my dependencies. In my case, the alamofire* ones.

**Comment by adrianodiasx93** [comment]
```
If you specify version requirements for your dependencies, that should help.

There's an issue where the dependency resolver struggles to find compatible versions of all the dependencies—so it tries older and older versions. Specifying version requirements prunes the search field.

This is something that Carthage should do better, but it requires a lot of work to get there.```

By @mdiep

**Comment by VPTeamMobile** [comment]
@adrianodiasx93 : your solution is not working for me. Could you give us your Cartfile for example ?

No one found another workaround ?
