### ISSUE TITLE
No such module 'FacebookCore'

### ISSUE THREAD

**Issue by khuong291** [facebook/facebook-sdk-swift#108]
I use pod to install this framework to my own framework. After I open my workspace and import ```
import FacebookCore
```

It says error: 

> 
No such module 'FacebookCore

'

Please help me to fix this. Thanks.

**Comment by xero88** [comment]
How do you resolve ? I got the same issue

**Comment by khuong291** [comment]
Could you show your project's hierarchy?

**Comment by AstafaKhan** [comment]
https://developers.facebook.com/docs/swift/getting-started
Follow these step!
You are follow wrong doc

**Comment by jerrychong25** [comment]
After you installed FacebookCore via Cocoapod, make sure you open Xcode project using **.xcworkspace** instead of **.xcodeproj**.

This is working on Xcode 10.2.

**Comment by AstafaKhan** [comment]
Yes, jerrychong25 it's working. when you installed Cocoapod every time we used .xcworkspace instead of .xcodeproj.

**Comment by AstafaKhan** [comment]
> After you installed FacebookCore via Cocoapod, make sure you open Xcode project using **.xcworkspace** instead of **.xcodeproj**.
> 
> This is working on Xcode 10.2.

yes, when we installed Cocoapod (any third party lib using of Cocoapod) we used .xcworkspace instead of .xcodeproj.

**Comment by AstafaKhan** [comment]
Hello Jerry,

Sorry for the late reply. Yes it's working

Sent from my iPhone


Warm Regards,

*Mohammad Astafa Khan*

*IOS Developer.*

AirWhizz
Mobile:* +91-798516117 <+91%2099540%2029889>*

<https://www.facebook.com/airwhizz>  <https://twitter.com/AirWhizz>
<http://instagram.com/airwhizzofficial>
<https://in.linkedin.com/company/airwhizz>

<http://www.airwhizz.com/>
