### ISSUE TITLE
Blank screen during login

### ISSUE THREAD

**Issue by ianzitow** [facebook/facebook-sdk-swift#109]
I've been using Facebook SDK (4.17.0) normally until iOS 10 and Swift 3. Running both on Simulator and device, the user is stuck at this screen:
![Simulator](https://cloud.githubusercontent.com/assets/2258901/20604278/c001d4aa-b24c-11e6-977d-1b828be074e0.png)

**Comment by ericpark** [comment]
Try adding this to your AppDelegate.swift.
   
 func application(_ application: UIApplication, open url: URL,sourceApplication: String?, annotation: Any) -> Bool {
        
        return SDKApplicationDelegate.shared.application(application, open: url as URL, sourceApplication: sourceApplication, annotation: annotation)
    }

**Comment by lindanordstrom** [comment]
the function above is being deprecated. Use the following:

```
import FacebookCore

...

    func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any] = [:]) -> Bool {
        return SDKApplicationDelegate.shared.application(app, open: url, options: options)
    }
```
