### ISSUE TITLE
When is pod 'FacebookShare' needed

### ISSUE THREAD

**Issue by kiwo12345** [facebook/facebook-sdk-swift#112]
I want to create a custom "login with facebook" button.

I want to authenticate the user and fetch their FB-id and email.

Do I need to include `FacebookShare` for this, Or can I just use FacebookCore and FacebookLogin?

**Comment by scoobydont** [comment]
For what you're trying to do, you would not require the FacebookShare. As per Facebook's documentation located here, 

https://developers.facebook.com/docs/swift/login

The code would look like this:

import FacebookCore
import FacebookLogin

func viewDidLoad() {    
  // Add a custom login button to your app
  let myLoginButton = UIButton(type: .Custom)]
  myLoginButton.backgroundColor = UIColor.darkGrayColor()
  myLoginButton.frame = CGRect(0, 0, 180, 40);
  myLoginButton.center = view.center;
  myLoginTitle.setTitle("My Login Button" forState: .Normal)

  // Handle clicks on the button
  myLoginButton.addTarget(self, action: @selector(self.loginButtonClicked) forControlEvents: .TouchUpInside) 

  // Add the button to the view
  view.addSubview(myLoginButton)
}

// Once the button is clicked, show the login dialog
@objc func loginButtonClicked() {
  let loginManager = LoginManager()
  loginManager.logIn([ .PublicProfile ], viewController: self) { loginResult in
    switch loginResult {
    case .Failed(let error): 
      print(error)
    case .Cancelled:
      print("User cancelled login.")
    case .Success(let grantedPermissions, let declinedPermissions, let accessToken):
      print("Logged in!")
  }
}

**Comment by nlutsenko** [comment]
Basically, what @scoobydont said.

FacebookCore - the core functionality of the SDK, things like App Events
FacebookLogin - the login functionality, including the login button and such
FacebookShare - the sharing functionality, so you can share custom or pre-defined types of content to Facebook from your apps.
