### ISSUE TITLE
FBSDKAccessTokenCacheV4 Crashes the application

### ISSUE THREAD

**Issue by frelei** [facebook/facebook-sdk-swift#115]
I ran the application and after sometime, the app crashes.
When the Facebook start the initialization the line 49 from the file FBSDKAccessTokenCacheV4 happens the problem.
Line error: 
`  if (![dict[kFBSDKAccessTokenUUIDKey] isEqualToString:uuid]) { `

And with the log: 

`
 *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSConcreteMutableData isEqualToString:]: unrecognized selector sent to instance 0x608000053ec0'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010a18034b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000109be121e objc_exception_throw + 48
	2   CoreFoundation                      0x000000010a1eff34 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x000000010a105c15 ___forwarding___ + 1013
	4   CoreFoundation                      0x000000010a105798 _CF_forwarding_prep_0 + 120
	5   FBSDKCoreKit                        0x0000000109076a4a -[FBSDKAccessTokenCacheV4 fetchAccessToken] + 202
	6   FBSDKCoreKit                        0x000000010907501c -[FBSDKAccessTokenCache fetchAccessToken] + 92
	7   FBSDKCoreKit                        0x0000000109083d1d -[FBSDKApplicationDelegate application:didFinishLaunchingWithOptions:] + 125
	8   Vouch                               0x0000000108b4bf42 _TFC5Vouch11AppDelegate11applicationfTCSo13UIApplication29didFinishLaunchingWithOptionsGSqGVs10DictionaryVSC29UIApplicationLaunchOptionsKeyP____Sb + 1442
	9   Vouch                               0x0000000108b4c544 _TToFC5Vouch11AppDelegate11applicationfTCSo13UIApplication29didFinishLaunchingWithOptionsGSqGVs10DictionaryVSC29UIApplicationLaunchOptionsKeyP____Sb + 180
	10  UIKit                               0x000000010af0a0be -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 290
	11  UIKit                               0x000000010af0ba43 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 4236
	12  UIKit                               0x000000010af11de9 -[UIApplication _runWithMainScene:transitionContext:completion:] + 1731
	13  UIKit                               0x000000010af0ef69 -[UIApplication workspaceDidEndTransaction:] + 188
	14  FrontBoardServices                  0x00000001127c0723 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 24
	15  FrontBoardServices                  0x00000001127c059c -[FBSSerialQueue _performNext] + 189
	16  FrontBoardServices                  0x00000001127c0925 -[FBSSerialQueue _performNextFromRunLoopSource] + 45
	17  CoreFoundation                      0x000000010a125311 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	18  CoreFoundation                      0x000000010a10a59c __CFRunLoopDoSources0 + 556
	19  CoreFoundation                      0x000000010a109a86 __CFRunLoopRun + 918
	20  CoreFoundation                      0x000000010a109494 CFRunLoopRunSpecific + 420
	21  UIKit                               0x000000010af0d7e6 -[UIApplication _run] + 434
	22  UIKit                               0x000000010af13964 UIApplicationMain + 159
	23  Vouch                               0x0000000108b4e7af main + 111
	24  libdyld.dylib                       0x000000010e1b368d start + 1
	25  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
`

**Comment by dingxuan92** [comment]
I have the same issue, were you able to solve it? I would appreciate some help please! Thank you!

**Comment by mltk96** [comment]
it's happening to me as well. any suggested solution?

**Comment by tericky** [comment]
In my case, using simulator iPhone 7 Plus (10.2) will crash every time launching.

**Comment by dingxuan92** [comment]
It happens to me as well! I reverted back to older version FBSDK 4.17 and it dosn't crash anymore.

**Comment by KHILL3000** [comment]
by revert you mean just go to the regular objective c version and using FBSDK instead of Facebook??

**Comment by KHILL3000** [comment]
https://developers.facebook.com/bugs/955908041210806/ subscribe here to get notified when the fix comes

**Comment by dingxuan92** [comment]
@KHILL3000 what I did was to use CocoaPod to revert the 4.18.0 version to 4.17.0.

For example my Podfile will look something like this, 

pod 'FBSDKCoreKit' "~> 4.17.0”; 
pod 'FBSDKLoginKit' "~> 4.17.0”;

**Comment by KHILL3000** [comment]
This has been fixed with the release of version 4.19.0 of the iOS SDK

**Comment by scalessec** [comment]
What's the correct way to fix this when installing via Carthage? eg: `github "facebook/Facebook-SDK-Swift"`? It's unclear to me how to bump the version of `FBSDKCoreKit` and `FBSDKLoginKit` when there isn't a new tag in this repo.
