### ISSUE TITLE
FBSDKShareDialog crashes on Swift 3.0

### ISSUE THREAD

**Issue by aymericio** [facebook/facebook-sdk-swift#117]
I get a crash on `FBSDKShareDialog` to share a video (or anything) via `MessageDialog`.

```swift
let video = Video(url: url)
let content = VideoShareContent(video: video)
let shareDialog = MessageDialog(content: content)
            
do {
    try shareDialog.show()
}
catch let error {
    print(error.localizedDescription)
}
```

Crash log
```
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**iOS:** 10.2
**Swift:** 3.0.0
**FacebookShare:** 0.20

**Comment by krezzoid** [comment]
@aymericio did you find a way to solve this issue?

**Comment by aymericio** [comment]
@krezzoid nope, I have not solved this issue for the moment :smirk:

**Comment by GSM412** [comment]
Did you find solution for this ?

**Comment by krezzoid** [comment]
@GSM412 check FB keys in your .plist - this crash happens if you missed something in .plist or put wrong FB configuration
