### ISSUE TITLE
FBSDKCoreKit, FBSDKLoginKit, FBSDKShareKit Info.plist files are missing proper CFBundleVersion.

### ISSUE THREAD

**Issue by AndrewBarba** [facebook/facebook-sdk-swift#12]
I think version 4.14 (CoreKit and LoginKit) are missing the `$(CURRENT_PROJECT_VERSION)` which gets set as `CFBundleVersion` in the Info.plist. I can confirm that the `FBSDKCoreKit.framework` in my local Carthage/Build folder is missing this key in the info.plist

**Comment by nlutsenko** [comment]
Yup, looks absolutely correct.
ObjC FBSDK has a slightly different release cycle than us (Swift SDK), meaning that releasing a fix for it won't be as fast.

Any chance CocoaPods is an option for you?
You could also always just change that Info.plist key manually, but there is no current way of automating that.

**Comment by AndrewBarba** [comment]
Okay makes sense. And yes, I have to use both Carthage and Cocoapods anyway so I'll just switch this sdk to CP for now. Do you want me to open the same issue in the other repo?

**Comment by AndrewBarba** [comment]
Hm nevermind, I don't think I can open issues in the other repo. If you could pass the word along, that would be awesome.

**Comment by nlutsenko** [comment]
Yup, creating an internal task and submitting a fix for it as well right now.

**Comment by AndrewBarba** [comment]
Amazing, really appreciate it. Thanks for the rapid responses

**Comment by JagCesar** [comment]
I just ran into the same issue, any eta on when this might be fixed @nlutsenko?

Thanks a bunch for creating this sdk btw. We can finally get rid of cocoa pods  :)

**Comment by nlutsenko** [comment]
:grin: The patch was merged upstream internally and it should be out with the next version of ObjC SDK in a few weeks.

**Comment by arsonik** [comment]
Hey, Any update on the ETA ?
Thanks alot !

**Comment by ashchan** [comment]
The iOS SDK v4.15 has been released two days ago. I tried updating my local carthage dependencies and it seems CFBundleVersion is properly set (as `4.15.0`).

**Comment by nlutsenko** [comment]
Hey guys, the bug is fully fixed now as of 4.15.0 of ObjC SDK. Yay!

This means that if you are using any package manager (like CocoaPods or Carthage) - you can get it today and successfully ship apps to App Store.

I am going to update few of the things in the Swift SDK in the upcoming days and we are going to ship `0.2` of it, which is likely to be the last Swift 2.3 release (Swift 3 GM is coming soon!), but it will also update all the references to the ObjC SDK, so everyone even installing from scratch always get the latest and greatest version.

**Comment by JagCesar** [comment]
These are great news! Keep up the good work guys! 👊🏼❤️

**Comment by Kacper20** [comment]
Hi @nlutsenko 

Am I seeing this right that version of Swift SDK (0.2.0) which should work(is backed by 4.15 of ObjC SDK) is Swift 3.0 only? Is there any way to use Carthage with Swift 2.3? Currently I can't build project properly because of bissing CFBundleVersion in Info.plist

Thanks for help,
