### ISSUE TITLE
Building FBSDKShareKit fails on version 0.2.0

### ISSUE THREAD

**Issue by Chandlerdea** [facebook/facebook-sdk-swift#120]
I am trying to build version 0.2.0 with carthage, but building FBSDKShareKit fails, which is preventing FacebookCore from being build. Here is the build error:
```
Undefined symbols for architecture arm64:
  "_CGContextFillEllipseInRect", referenced from:
      +[FBSDKShareUtility imageWithCircleColor:canvasSize:circleSize:] in FBSDKShareUtility.o
ld: symbol(s) not found for architecture arm64
```

This happens when the ```FBSDKShareKit_TV-Dynamic``` scheme is building.

**Comment by asowers1** [comment]
I'm having the same issue.

**Comment by Tsymlov** [comment]
I'm also having the same issue.

**Comment by asowers1** [comment]
Has anyone found a resolution for this yet?

**Comment by mrojas** [comment]
Same here

**Comment by Chandlerdea** [comment]
Looks like Facebook doesn't really care about maintaining their SDKs.

**Comment by QuynhNguyen** [comment]
if you don't really care about tvOS then you can pass in `--platform ios` in order to skip the broken build.

**Comment by christophereagan** [comment]
> you can pass in --platform ios in order to skip the broken build.

Where do you pass that?
