### ISSUE TITLE
Logged in state not persisting across app starts

### ISSUE THREAD

**Issue by mikemags1** [facebook/facebook-sdk-swift#124]
FBSDKAccessToken.current() works only after explicitly logging in a user every session.

**Comment by mikeknapp** [comment]
I found a workaround in [this article](http://stackoverflow.com/questions/32896269/ios-9-facebook-access-token-is-nil-on-future-app-launches)

1. Add this line inside ` didFinishLaunchingWithOptions`:

```swift
FBSDKApplicationDelegate.sharedInstance().application(application, didFinishLaunchingWithOptions: launchOptions)
```

2. Downgrade to the 4.17.0 versions of `FBSDKCoreKit` and `FBSDKLoginKit`.

That worked for me.
