### ISSUE TITLE
LinkShareContent.quote not working

### ISSUE THREAD

**Issue by Niroj08** [facebook/facebook-sdk-swift#125]
Seems like "quote" param is not working in iOS with build version 0.1.1 while works fine on android
0.2.0 dosent seems to build properly so have to use older version

as well when i use the "description" param, the description is set to the share dialog but can't find in facebook after its been shared.

as described in http://stackoverflow.com/questions/30742645/facebook-sdk-share-link-content-gets-replaced-by-meta-data-from-content-url
The description for application link from app store and play store is neglected

**Comment by johnnysparks** [comment]
I was struggling with this today. After some trial and error I noticed that the `quote` param only worked when the url was properly formatted: 

 * Notice the difference in the `contentURL`, the broken quote lacks the `https` scheme. It may be that if there are other errors with the url it won't work properly either.

**Broken:**
<img width="541" alt="screen shot 2017-02-08 at 3 18 13 pm" src="https://cloud.githubusercontent.com/assets/586820/22762008/f9f48198-ee11-11e6-9f39-a142d1ae9fe7.png">
<img width="250" src="https://cloud.githubusercontent.com/assets/586820/22762018/0472d4da-ee12-11e6-9f95-545715323a9c.PNG">


**Working:**
<img width="538" alt="screen shot 2017-02-08 at 3 15 50 pm" src="https://cloud.githubusercontent.com/assets/586820/22762039/29e35b2c-ee12-11e6-9e67-9b4e1fa6d41a.png">
<img width="250" src="https://cloud.githubusercontent.com/assets/586820/22762041/2dc78ce0-ee12-11e6-9a37-c7777cf24ff1.PNG">

Hope that's helpful.

**Comment by beltik** [comment]
I solve this by change dialog mode to something like web mode, to avoid open native facebook app.

**Comment by gregorpichler** [comment]
Hi, I'm facing the same problem, however my link seems to be properly formatted. I'm creating the dialog as seen below and I'm using FBSDKShareKit 4.28.0 and FacebookShare 0.3.0. It opens the Messenger app however the `quote`is not shown.

`let content = LinkShareContent(url: URL(string: link)!, quote: "Join the event by clicking on the link")
let shareDialog = MessageDialog(content: content)`

![shareinviteviewcontroller_swift](https://user-images.githubusercontent.com/4091405/33073021-d422fa3a-cec1-11e7-91b7-d105836d2e9d.jpg)

**Comment by guillermoap** [comment]
I'm having this same issue, are there any updates on this?

**Comment by cecgsn** [comment]
+1 to having this reopened, the quote doesn't seem to be working on native ShareDialogMode, I had to use WebBrowser for it to work

**Comment by codytwinton** [comment]
This should be fixed with the latest version of the iOS SDK that this SDK relies on. In addition, I'm in process of releasing `0.3.3`.

**Comment by codytwinton** [comment]
@abdelrahman-badary - Updated:

* `FacebookCore -> 0.3.3`
* `FacebookLogin -> 0.3.3`
* `FacebookShare -> 0.3.3`

* `FBSDKCoreKit -> 4.36.0`
* `FBSDKLoginKit -> 4.36.0`
* `FBSDKShareKit -> 4.36.0`
