### ISSUE TITLE
ReadME Incomplete

### ISSUE THREAD

**Issue by JaapWeijland** [facebook/facebook-sdk-swift#126]
Neither on developers.facebook.com as in the readme was documented how the appdelegate.swift should be configured. Only the Objective-C version is explained. Please include this file into the readme and on developers.facebook.com: https://github.com/facebook/facebook-sdk-swift/blob/master/Samples/Catalog/Sources/AppDelegate.swift

**Comment by NikKovIos** [comment]
Also, why FBSDK called as SDK?

**Comment by asowers1** [comment]
@NikKovIos I also have this question. That seems like an inappropriate namespace.
