### ISSUE TITLE
Issue using OpenGraphShareContent with share dialog

### ISSUE THREAD

**Issue by RPCarter53** [facebook/facebook-sdk-swift#138]
I am trying to post an OpenGraph story by following the examples on-line. The following lines fail to compile..

        let content = OpenGraphShareContent(action: action, previewPropertyName: "jigsaw")        
        try? ShareDialog.show(from: self, content: content)

 There is a compile error on the last of these - "Generic parameter 'Content' could not be inferred"

CocoaPods reports the following versions - 
Using FBSDKCoreKit (4.20.1)
Using FBSDKShareKit (4.20.1)
Using FacebookCore (0.2.0)
Using FacebookShare (0.2.0)

**Comment by RPCarter53** [comment]
I note this is a duplicate of #105 and #132!

**Comment by RPCarter53** [comment]
This issue can be worked around with the following simple extension. The association to the ContentProtocol is missing in the original source.

extension OpenGraphShareContent : ContentProtocol {
    }

Beyond this however other problems will arise due to a faulty initiator for OpenGraphPropertyName. The initiator with suggested corrections is..

  public init?(_ string: String) {
    // let components = string.characters.split(separator: ":")
    let components = string.characters.split(separator: ":", maxSplits: 1) // suggested alternative
    guard components.count >= 2 else {
      return nil
    }

    self.namespace = String(components[0])
    self.name = String(components[1])   // suggested alternaive

    // The following original gives array index out of range and an invalid build of name
    //let subcharacters = components[1 ... components.count]
    //self.name = subcharacters.reduce("", { $0 + ":" + String($1) })
  }

**Comment by dirtyhenry** [comment]
Wow, I'm running into this issue today. Is this project still active Facebook? :)

**Comment by RPCarter53** [comment]
I think as the problem is still there after all these months it is safe to assume the project is no actively maintained. We moved to a SharePhoto option rather than OpenGraph as the custom stories have been deprecated by Facebook.
