### ISSUE TITLE
Is this repo dead?

### ISSUE THREAD

**Issue by exocode** [facebook/facebook-sdk-swift#139]
since months no commit. Not compiling with Xcode 8.x. not with carthage. not with cocoapods. 

Any alternatives? 

The objectiveC-Version?

or that one: https://developers.facebook.com/docs/ios/getting-started ?

__Thanks for your repsone__

**Comment by oiledCode** [comment]
@nlutsenko it would be great if you can answer.

**Comment by nlutsenko** [comment]
Nope, things are alive. 😁 
I didn't have a lot of time to be able to update few things here, but as we go forward, taking into account number of people interested in using this - going to try my best to maintain and update all things here, so you guys get the best support possible.
