### ISSUE TITLE
Include of non-modular header inside framework module 'FBSDKCoreKit.FBSDKAccessToken'

### ISSUE THREAD

**Issue by AdventuresOfMar** [facebook/facebook-sdk-swift#14]
I've been searching low and high to find an answer for this issue and I've already changed my Allow non-modular setting to yes. I'm still not sure why my project won't build when installing Facebook SDK via cocoapods I'm using Xcode 9.3.1

**Comment by nlutsenko** [comment]
I would recommend quitting Xcode, completely removing Xcode's DerivedData folder (including from trash) and re-running `pod update` and trying once again.
The current latest release successfully installs via CocoaPods and runs no problem, but sometimes stale cache/old files might be intervening with the source code when run from Xcode.

**Comment by mickeysox** [comment]
Tried that, doesn't work.

New project in Xcode 7.3.1
podfile:

platform :ios, "8.0"
use_frameworks!

pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'

Any other ideas?

**Comment by nlutsenko** [comment]
- Try removing `Pods`/`Podfile.lock` completely.
- Then running `pod init` and inside your target's list of pods - declare them.

Also, quick question, could you confirm the version of your CocoaPods by running `pod --version`?

**Comment by nlutsenko** [comment]
Also, would be helpful if you could archive the new project and attach it here, so we can reproduce the problem.

**Comment by mickeysox** [comment]
HI nlutsenko,

problem solved... thanks for your help.  Just to confirm, the steps I took were:

1. Deleted /Users/development/Library/Developer/Xcode/DerivedData - I don't know if this had any bearing as I tried this directly after but the errors still appeared.

2. Updated cocoapods to 1.0.1 - I was on 0.39 or something like that.

3. Pod init... edited the Podfile...

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'test' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for test
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
end

4. Opened Xcode via the xcworkspace file and voila, no errors.

Thanks again.

**Comment by nlutsenko** [comment]
And I think the problem was an old installation of CocoaPods (0.39 vs 1.0.1)
Glad this helped!

**Comment by mikeRozen** [comment]
Hi **nlutsenko** ,
I have the same issue. 
I have tried everything suggested above including ALL possible _Cleaning magic_. I also reinstalled gems and pods to the last version (1.2.1).
I deleted my pods including podFileLock I reinstalled everything from beginning and still have this issue.

```
platform :ios, '9.0'
use_frameworks!

target 'driveNpass' do
    pod JASON,  ~> '3.0'
    pod 'FMDB'
    pod 'Alamofire', ' ~> 4.0'
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'FBSDKShareKit'
    pod 'SDWebImage', '~>3.8'
    pod 'AZSClient'
    pod 'AwesomeCache', :git => 'https://github.com/aschuch/AwesomeCache.git', :branch => 'master'
    #pod 'JTAppleCalendar'
end
```
I changed Search path headers / Framework to every possible variations but NO luck.
Just small thing that I noticed my _Pods/Headres_ folder is EMPTY, while in other project (which written in Objective-C) I can see all the Links to my headers (Objective-C pods was installed via 1.1.1 version).
I really have no idea what else can i try.
Please Help.

**Comment by cherpake** [comment]
Yeah same issue here.. nothing helps.

**Comment by spotelf13** [comment]
Updating cocoapods fixed a similar issue for me.
