### ISSUE TITLE
Was FBSDKAppLinkUtility.fetchDeferredAppLink() removed?

### ISSUE THREAD

**Issue by Daltron** [facebook/facebook-sdk-swift#140]
I recently converted over from the Objective-C SDK to the Swift SDK and noticed that there doesn't seem to be any support for the FBSDKAppLinkUtility.fetchDeferredAppLink() function that was in the Objective-C SDK. Is this automatically handled now within the Swift SDK or was it renamed to something else?

**Comment by zhihuitang** [comment]
same question

**Comment by erichsu** [comment]
+1

**Comment by asos-stefanop** [comment]
+ 1

**Comment by omake43** [comment]
+1

**Comment by Alex1989Wang** [comment]
Does this deferred app link still work? Even using the Objective-C SDK, I'm not able to get this to work.

**Comment by lostatseajoshua** [comment]
The method still exists here:
https://github.com/facebook/facebook-ios-sdk/blob/2403325147f46db57f0afed1039d8b2bd1dd7f46/FBSDKCoreKit/FBSDKCoreKit/FBSDKAppLinkUtility.m#L34

I was able to call the method in the sample project with this code:

    // import
    import FBSDKCoreKit.FBSDKAppLinkUtility

    // within a function
    FBSDKAppLinkUtility.fetchDeferredAppLink { (url, error) in
      if (error != nil) {
        return
      }
    }

Let me know if you have any other trouble with this.
