### ISSUE TITLE
There are problems with Swift 3.1 and Facebook SDK 4.20.2

### ISSUE THREAD

**Issue by applehawk** [facebook/facebook-sdk-swift#143]
The following build commands failed:
        CompileC /Users/vlad/Library/Caches/org.carthage.CarthageKit/DerivedData/facebook-ios-sdk/sdk-version-4.20.2/Build/Intermediates/FBSDKCoreKit.build/Release-iphoneos/FBSDKCoreKit-Dynamic.build/Objects-normal/armv7/FBSDKGraphRequestPiggybackManager.o FBSDKCoreKit/Internal/Network/FBSDKGraphRequestPiggybackManager.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
~

**Comment by AndrewSB** [comment]
this dupes #142
