### ISSUE TITLE
shareDialog thumbnail picture missing

### ISSUE THREAD

**Issue by wk633** [facebook/facebook-sdk-swift#150]
Hi I am trying to use this sdk to share a link by shareDialog, but I find that the thumbnail picture which is passed by "imageURL" is missing.

```
let content = LinkShareContent(url: NSURL(string: self.imageUrl) as URL!, title: "test title", description: "test description", imageURL: NSURL(string: self.imageUrl) as URL!)
let shareDialog = ShareDialog(content: content)
        
shareDialog.mode = .feedBrowser
shareDialog.failsOnInvalidData = true
shareDialog.completion = { result in
        print(result)
}
 do {
      try shareDialog.show()
}catch {
      print("error!!!")
}
```
<img width="375" alt="111" src="https://cloud.githubusercontent.com/assets/24535632/25384656/05f9038e-2976-11e7-844e-b2708de1fcdc.png">

I am sure this url is passed to LinkShareContent.swift and is a valid url, but I don't know why this picture did not show.

the url is 
https://scontent.xx.fbcdn.net/v/t1.0-1/c6.7.60.60/p74x74/11174920_985696921454760_2198316150351235477_n.jpg?oh=4bd1d5a2383827fb0d4bad55dbe019a2&oe=59992AF0

**Comment by wk633** [comment]
I have fixed this problem. The reason is that the resolution of this picture is too low.

**Comment by kristoff2016** [comment]
Hi, does it work for you ?
