### ISSUE TITLE
Unresolved loginManager

### ISSUE THREAD

**Issue by ALAxHxC** [facebook/facebook-sdk-swift#153]
Hi, im working with Facebook SDK in swift3

Frist int my pod:

> target ‘ProcIOS’ do
> pod 'MOCA'
> pod 'Toast-Swift', '~> 2.0.0'
> pod 'AMTooltip'
> pod 'Firebase'
> pod 'Firebase/Core'
> pod 'Firebase/Auth'
> pod 'Firebase/Database'
> pod 'FacebookCore'
> pod 'FacebookLogin'
> use_frameworks!
> end

Second , header

#import <FBSDKCoreKit/FBSDKCoreKit.h>
#import <FBSDKLoginKit/FBSDKLoginKit.h>

Third

appdelegate:

```
 func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        MOCA.initializeSDK()
        FIRApp.configure()
        let bool = SDKApplicationDelegate.shared.application(application, didFinishLaunchingWithOptions: launchOptions)
        FBSDKProfile.enableUpdates(onAccessTokenChange: true)
        return bool
    }

 func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey: Any] = [:]) -> Bool {
        return FBSDKApplicationDelegate.sharedInstance().application(app, open: url, options: options)
    }
```

And final in my app:

```
import FacebookCore
import FacebookLogin
```
` let loginManager = LoginManager()`

Show me: Use unresolved identifier LoginManager

**Comment by KarthikSankar29** [comment]
@ALAxHxC Still facing this issue ?

**Comment by ALAxHxC** [comment]
Yeah I can't resolve,
clean pod, update, remove, all but doesn't work

**Comment by BigAlKo** [comment]
Same Issue, any ideas?

**Comment by italoBianchini** [comment]
Same Issue, any ideas?

**Comment by italoBianchini** [comment]
let loginManager = FBSDKLoginManager()

**Comment by sankalapdew** [comment]
Same issue, any idea to resolve it.

**Comment by mouchegmouradian** [comment]
Same issue here for LoginManager, SDKApplicationDelegate, AccessToken... 

Everything was working fine. I did a pod update and got (FacebookCore, FacebookLogin v 0.7.0) and these errors appeared

**Comment by Galeas** [comment]
I decided to rollback to the previous version until it is fixed
```ruby
pod 'FacebookCore', '~> 0.5.0'
pod 'FacebookLogin', '~> 0.5.0'
```

**Comment by doruchidean-lifeishard** [comment]
@lostatseajoshua Could you please comment your decision to close this issue?
