### ISSUE TITLE
Include of non-modular header inside framework module 'FBSDKCoreKit.FBSDKAccessToken'

### ISSUE THREAD

**Issue by mikeRozen** [facebook/facebook-sdk-swift#154]
Hi  ,
I have the same issue as [this.](https://github.com/facebook/facebook-sdk-swift/issues/14).
I have tried everything  proposed in the thread above, also it seems that above issue was closed (so I didn't get any answer )but the problem still exists.  
I have tried everything suggested above including ALL possible _Cleaning magic_. I also reinstalled gems and pods to the last version (1.2.1).
I deleted my pods including podFileLock I reinstalled everything from beginning and still have this issue.

```
platform :ios, '9.0'
use_frameworks!

target 'driveNpass' do
    pod JASON,  ~> '3.0'
    pod 'FMDB'
    pod 'Alamofire', ' ~> 4.0'
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'FBSDKShareKit'
    pod 'SDWebImage', '~>3.8'
    pod 'AZSClient'
    pod 'AwesomeCache', :git => 'https://github.com/aschuch/AwesomeCache.git', :branch => 'master'
    #pod 'JTAppleCalendar'
end
```
I changed Search path headers / Framework to every possible variations but NO luck.
I also switched _Allow non-modular includes_ in the target to YES,NO but NO luck.
Just small thing that I noticed my _Pods/Headres_ folder is EMPTY, while in other project (which written in Objective-C) I can see all the Links to my headers (Objective-C project pods was installed via 1.1.1 version). 
I believe it started to happen after I made an update from 0.3.9 to 1.1.1 (not sure about it). 
I really have no idea what else can i try.
Please Help.

**Comment by mikeRozen** [comment]
I solved my issue.
According to apple:

> This happens because in 7.1:
The Swift compiler is stricter about including non-modular header files than it was in previous releases. Debugging a Swift target requires that frameworks be properly modular, meaning all of the publicly-imported headers are either accounted for in the framework's umbrella header, are imported from another modular framework, or are listed explicitly in a custom module.modulemap file (advanced users only).
The compiler will run into issues if the same header file is accessible both through Header Search Paths (`-I`, `-isystem`) and Framework Search Paths (`-F`, `-iframework`), even if there are symbolic links involved. In these cases, you should prefer using Framework Search Paths. (Note that this invalid configuration may be generated by external systems, such as CocoaPods.)

From this [link](https://forums.developer.apple.com/thread/23554)

I belive I still had Search Header paths from the old cocaoPods with search Framework path.

**Comment by steverob** [comment]
@mikeRozen  What did you actually do that solved the issue for you with OpenTok?
