### ISSUE TITLE
Fix Carthage integration

### ISSUE THREAD

**Issue by adrianm2000** [facebook/facebook-sdk-swift#155]
If you're going to support Carthage integration, then please fix it and keep it current. Otherwise, remove the option from the integration instructions, or AT LEAST update the requirements to state that the current version of Xcode or Swift or whatever isn't supported so we don't spend a lot of time chasing down your errors. It defeats the purpose of using dependency management.

**Comment by leszarna** [comment]
This configuration works at the moment:
carthage version
0.18.1

github "facebook/facebook-sdk-swift" "master"
github "facebook/facebook-ios-sdk" "sdk-version-4.21.0"

**Comment by Appendit** [comment]
Which Xcode version were you using?

Building scheme "FBSDKShareKit_TV-Dynamic" in FacebookSDK.xcworkspace
Build Failed
	Task failed with exit code 65:

With Xcode 8.3.3

**Comment by hixfield** [comment]
Same here!

**Comment by teonicel** [comment]
Hi i get this  when i try to update the carthage:
*** Downloading facebook-ios-sdk.framework binary at "4.24.0"
*** Checking out facebook-ios-sdk at "sdk-version-4.24.0"
*** Checking out Facebook-SDK-Swift at "0.2.0"
A shell task (/usr/bin/env git submodule --quiet update --init --recursive) failed with exit code 1:
fatal: unable to connect to github.com:
github.com[0: 192.30.253.113]: errno=Operation timed out
github.com[1: 192.30.253.112]: errno=Operation timed out

fatal: clone of 'git://github.com/BoltsFramework/Bolts-iOS.git' into submodule path '/Users/teonicel/Documents/ioslibs/carthage/Carthage/Checkouts/Facebook-SDK-Swift/Carthage/Checkouts/facebook-ios-sdk/Bolts-IOS' failed
Failed to clone 'Bolts-IOS'. Retry scheduled
fatal: unable to connect to github.com:
github.com[0: 192.30.253.113]: errno=Operation timed out
github.com[1: 192.30.253.112]: errno=Operation timed out

fatal: clone of 'git://github.com/erikdoe/ocmock' into submodule path '/Users/teonicel/Documents/ioslibs/carthage/Carthage/Checkouts/Facebook-SDK-Swift/Carthage/Checkouts/facebook-ios-sdk/vendor/OCMock' failed
Failed to clone 'vendor/OCMock'. Retry scheduled
fatal: unable to connect to github.com:
github.com[0: 192.30.253.113]: errno=Operation timed out
github.com[1: 192.30.253.112]: errno=Operation timed out

fatal: clone of 'git://github.com/AliSoftware/OHHTTPStubs.git' into submodule path '/Users/teonicel/Documents/ioslibs/carthage/Carthage/Checkouts/Facebook-SDK-Swift/Carthage/Checkouts/facebook-ios-sdk/vendor/OHHTTPStubs' failed
Failed to clone 'vendor/OHHTTPStubs'. Retry scheduled
fatal: unable to connect to github.com:
github.com[0: 192.30.253.112]: errno=Operation timed out
github.com[1: 192.30.253.113]: errno=Operation timed out

fatal: clone of 'git://github.com/tomaz/appledoc.git' into submodule path '/Users/teonicel/Documents/ioslibs/carthage/Carthage/Checkouts/Facebook-SDK-Swift/Carthage/Checkouts/facebook-ios-sdk/vendor/appledoc' failed
Failed to clone 'vendor/appledoc'. Retry scheduled
fatal: unable to connect to github.com:
github.com[0: 192.30.253.112]: errno=Operation timed out
github.com[1: 192.30.253.113]: errno=Operation timed out

fatal: clone of 'git://github.com/facebook/ios-snapshot-test-case.git' into submodule path '/Users/teonicel/Documents/ioslibs/carthage/Carthage/Checkouts/Facebook-SDK-Swift/Carthage/Checkouts/facebook-ios-sdk/vendor/ios-snapshot-test-case' failed
Failed to clone 'vendor/ios-snapshot-test-case'. Retry scheduled
fatal: unable to connect to github.com:
github.com[0: 192.30.253.113]: errno=Operation timed out
github.com[1: 192.30.253.112]: errno=Operation timed out

fatal: clone of 'git://github.com/facebook/xctool.git' into submodule path '/Users/teonicel/Documents/ioslibs/carthage/Carthage/Checkouts/Facebook-SDK-Swift/Carthage/Checkouts/facebook-ios-sdk/vendor/xctool' failed
Failed to clone 'vendor/xctool'. Retry scheduled
fatal: unable to connect to github.com:
github.com[0: 192.30.253.113]: errno=Operation timed out
github.com[1: 192.30.253.112]: errno=Operation timed out

fatal: clone of 'git://github.com/BoltsFramework/Bolts-iOS.git' into submodule path '/Users/teonicel/Documents/ioslibs/carthage/Carthage/Checkouts/Facebook-SDK-Swift/Carthage/Checkouts/facebook-ios-sdk/Bolts-IOS' failed
Failed to clone 'Bolts-IOS' a second time, aborting

**Comment by startupthekid** [comment]
It's 2018, why do simple things like this not work? You *cant* say you support Carthage and then not actively maintain it. The solution should never be to just download the master branch, that's bad practice and consumers of the framework should be able to download any arbitrarily tagged release. It's quite clear that facebook doesn't care about it's iOS developers. I've been an iOS developer for almost a decade and one of my biggest pain points across all those years and multiple projects and teams? Working with facebook developer portal/facebook open source. Whether it's terrible or out of date documentation to **tagged and publish releases that don't compile** (how does that even happen), it's taken up so much time from my developmen. I've lost so much time from my life trying to deal with the sdks that this company produces that I gave up and on principle, will not be supporting facebook login or any other facebook features going forward. I highly suggest all other developers do the same, its the only way facebook will start taking how they support the developer community seriously.
