### ISSUE TITLE
XCode 8.3.1 Appdelegate open url

### ISSUE THREAD

**Issue by shanmarkus** [facebook/facebook-sdk-swift#158]
<img width="1192" alt="screen shot 2017-05-26 at 2 37 24 pm" src="https://cloud.githubusercontent.com/assets/3590755/26485349/f3d0bada-4220-11e7-8d1f-20e5d6689789.png">

Anything did i missed ? Thank you so much

**Comment by ikbalyasarGis** [comment]
.sharedInstance().application(app, open:url as URL, options: options) 

try this

**Comment by shanmarkus** [comment]
Still not working @ikbalyasarGis 😢 

<img width="1109" alt="screen shot 2017-05-31 at 9 21 19 am" src="https://cloud.githubusercontent.com/assets/3590755/26612982/8acb28a2-45e2-11e7-89cd-7121dc0ea154.png">
