### ISSUE TITLE
dyld: Library not loaded: @rpath/FBSDKLoginKit.framework/FBSDKLoginKit   Referenced from: /Users/development/Library/Developer/CoreSimulator/Devices/CFD9201A-7745-42C1-AACC-66422917F80D/data/Containers/Bundle/Application/07DA2FF2-144A-4556-8D94-A9AA179AA52E/test.app/test   Reason: image not found

### ISSUE THREAD

**Issue by mickeysox** [facebook/facebook-sdk-swift#16]
Hi,

I have successfully installed the Facebook SDK via cocoapods, however once the simulator is up and running, I receive this error:

```
dyld: Library not loaded: @rpath/FBSDKLoginKit.framework/FBSDKLoginKit
  Referenced from: /Users/development/Library/Developer/CoreSimulator/Devices/CFD9201A-7745-42C1-AACC-66422917F80D/data/Containers/Bundle/Application/07DA2FF2-144A-4556-8D94-A9AA179AA52E/test.app/test
  Reason: image not found
```
I have cleared down all files that are in Devices and closed Xcode but this keeps appearing.

It also breaks on this:

```
dyld_sim`dyld_fatal_error:
    0x104237000 <+0>: int3   
->  0x104237001 <+1>: nop  
```

**Comment by nlutsenko** [comment]
This technically means that FBSDKLoginKit dependency is missing from the list of linked frameworks. 
Any chance you can share your Podfile and project setup here so we can investigate. 
I would also recommend double checking that pods are properly integrated with your app target.

**Comment by mickeysox** [comment]
HI,

the pod file is:

`# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'test' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for test
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
end
`

standard swift project for Xcode 7.3.1.  No code added - standard build.

I have tried recreating the project a few times, but without luck.

**Comment by mickeysox** [comment]
[test.zip](https://github.com/facebook/facebook-sdk-swift/files/366978/test.zip)
xcode file attached if you would like to try and replicate.

**Comment by nlutsenko** [comment]
Awesome, the attachment always helps!
Digging into it right now.

**Comment by mickeysox** [comment]
Hmmmm, ok so I have just downloaded the project from here and run it in my downloads folder but the error no longer appears.

I re-run it in my development folder, and it does appear.  This is strange...

**Comment by nlutsenko** [comment]
Looks like you have manually added all the frameworks (FBSDKLoginKit, FBSDKCoreKit and such to the list of "Frameworks") from disk?
Not sure if it's intended, but I can't quite get this to reproduce locally.
Also, are you running via a `Test.xcworkspace` or `Test.xcodeproj`? To make CocoaPods work - it should always be the former.

**Comment by mickeysox** [comment]
Ahh yes, apologies, I added those after you mentioned it might not be linking those frameworks correctly.  Let me create a clean version for you.

**Comment by nlutsenko** [comment]
(y) Please also make sure you close the xcodeproj and re-open via a workspace, since the project will lack the implicit dependencies that CocoaPods is creating.

**Comment by nlutsenko** [comment]
In any way, please let me know how it goes.

**Comment by mickeysox** [comment]
OK, so it seems as though if I create another project say test_v2 it works fine, both on my desktop and in my development folder.  However if I recreate a test project in my development folder, the error appears.  So it feels like there is a project called test somewhere that is corrupt?  Any ideas where that could be so I could clear it out?

**Comment by nlutsenko** [comment]
I would look at the Xcode's DerivedData and check maybe there is something stale there that needs to be cleaned up.
Glad you found the solution though to the original problem.

**Comment by mickeysox** [comment]
Cool, so I have cleared out my DerivedData folder and I now have a working project named test.  Xcode... so fussy!  Thanks for the support.
