### ISSUE TITLE
I received "Swift Compiler Error" warning when try to run

### ISSUE THREAD

**Issue by ismailcaferoglu** [facebook/facebook-sdk-swift#161]
When I tried to run the project I saw this warning in UserProfilePictureView.swift

"Swift Compiler Error"
No such module 'UIKIT'

How can I solve this problem?

**Comment by ravikumar2015ios** [comment]
same  problem give me answer?

**Comment by ravikumar2015ios** [comment]
i'm also facing same problem?

**Comment by KieranLafferty** [comment]
+1

**Comment by codytwinton** [comment]
@ismailcaferoglu - I'm in process of closing old issues to help us focus on improving this SDK. If you're still running into this issue, please feel free to reopen this issue.
