### ISSUE TITLE
Does not compile with Swift 4

### ISSUE THREAD

**Issue by ldiqual** [facebook/facebook-sdk-swift#162]
I get the following errors when trying to compile with Swift 4:

```
Sources/Core/AppEvents/AppEvent.Builtin.swift:125:78: 'toUIntMax()' is unavailable
Sources/Core/AppEvents/AppEvent.Builtin.swift:239:68: 'toUIntMax()' is unavailable
Sources/Core/GraphRequest/GraphRequestProtocol.Bridge.swift:25:68: Closure tuple parameter '(key: String, value: Any)' does not support destructuring
```

**Comment by xisintag** [comment]
I get the same errors. Did anyone found a replacement for toUIntMax() under Swift 4?

**Comment by Zf97** [comment]
"$0.toUIntMax() as UInt64" should be replaced with UInt64($0)

**Comment by mortocks** [comment]
+1

**Comment by Henriquedrdc** [comment]
+1

**Comment by Henriquedrdc** [comment]
+1

**Comment by imairi** [comment]
+1

**Comment by srea** [comment]
+1

**Comment by donpironet** [comment]
+1

**Comment by gbhall** [comment]
Is there a workaround for this? I can't progress with Facebook integration until this is resolved.

**Comment by Ged2323** [comment]
Hello,

Has anyone had this error?

Cannot subscript a value of type 'String.UnicodeScalarView' with an index of type 'CountableRange<String.UnicodeScalarView.IndexDistance>' (aka 'CountableRange<Int>')

Thanks in advance for your help.

**Comment by carlhung** [comment]
you mean this line?
cleaned[range].map(Character.init)

I want to fix this as well. which causes 'CountableRange<String.UnicodeScalarView.IndexDistance>' (aka 'CountableRange')

**Comment by carlhung** [comment]
I use this piece of code:
    let substr = String(cleaned)
    if substr.characters.count > 10 {
        let endIndex = substr.index(substr.startIndex, offsetBy: 9)
        return String(substr[substr.startIndex...endIndex])
    } else {
        return substr
    }

to replace this piece:
let range = 0 ..< min(10, cleaned.count)
let characters = cleaned[range].map(Character.init)
return String(characters)

I don't know if it would work well.

**Comment by dmr07** [comment]
Any updates on this?

**Comment by hankchen1728** [comment]
try this:
```let range = String.Index(encodedOffset: 0) ..< String.Index(encodedOffset: min(10, cleaned.count)) ```
to replace `let range = 0 ..< min(10, cleaned.count)`

Range of string subscript need to be 'Range<String.UnicodeScalarView.Index>',
but 0,10,and cleaned.count are 'Int'
change 'Int' to 'String.Index' may solve this

**Comment by irace** [comment]
Is Facebook no longer maintaining this library?

**Comment by gbhall** [comment]
I think Facebook don't work on prerelease software, as nothing is final yet and Apple could still make any change they want to.

**Comment by dpopov** [comment]
@gbhall  XCode is in GM. So this is no longer "prerelease software"

**Comment by tom-wolters** [comment]
So... Any update in sight?

**Comment by gbhall** [comment]
I would suggest filing a bug report on Facebook's developer bug report
website and posting the bug report link back here.

**Comment by jasonwedepohl** [comment]
+1

**Comment by julienfouilhe** [comment]
PR #169 would resolve the problem, any update on this? Thanks!

**Comment by SunDog** [comment]
+1

**Comment by pedantix** [comment]
+1, because its the thing to do

**Comment by Said-Re** [comment]
+1

**Comment by francisykl-91** [comment]
+1

**Comment by reddioment** [comment]
I collected all the errors and fixes and created this tutorial on [compileing the Swift SDK in Swift 4](http://www.kristofk.com/facebook-swift-sdk-updated-to-swift-4/)

**Comment by grudev** [comment]
+1

**Comment by ricardo0100** [comment]
+1

**Comment by ethansinjin** [comment]
+1

**Comment by ppcat** [comment]
+1

**Comment by soponcv** [comment]
+1

**Comment by nbtolegenov** [comment]
+1

**Comment by julienfouilhe** [comment]
Guys, it's coming, see #184. Thanks to @gfosco for taking care of this!

**Comment by gfosco** [comment]
0.3.0 is being published as we speak. :)

**Comment by ArsalanWahid** [comment]
Even 0.3.0 has the same errors and what made me find this thread

**Comment by julienfouilhe** [comment]
@ArsalanWahid I don't have any problem with 0.3.0. What kind of errors do you have?

**Comment by vzaoral** [comment]
For me same error (0.3.0, Swift 4) - _toUIntMax() obsoleted_

**Comment by khoatd92** [comment]
For me same error! Could anyone take a look on it please?
AppEvent.Builtin.swift:125:78: 'toUIntMax()' is unavailable

**Comment by jay-citrin** [comment]
+1

**Comment by ppcat** [comment]
After performing `pod update` from 0.2.0 to 0.3.0. It works~

**Comment by gholias** [comment]
Cocoapods still cant find version 0.3.0

is there any solution to the problem?

**Comment by AlexandreRamos** [comment]
After running pod update, you will have the following information in your terminal:

Installing FBSDKCoreKit 4.27.1 (was 4.27.0)
Installing FBSDKLoginKit 4.27.1 (was 4.27.0)
Installing FBSDKShareKit 4.27.1 (was 4.27.0)
Installing FacebookCore 0.3.0 (was 0.2.0)
Installing FacebookLogin 0.3.0 (was 0.2.0)
Installing FacebookShare 0.3.0 (was 0.2.0)

**Comment by julienfouilhe** [comment]
And don't forget to `pod repo update` to get the latest versions. (cc @gholias)

**Comment by gholias** [comment]
I found out the problem, the **'FBSDKCoreKit'** pod had a fixed old version that was blocking the usage of the version 0.3.0.

Everything is working now, thanks a lot for help.

**Comment by Khodour** [comment]
Facebook should hair new iOS developers XD why this issue not yet fixed !!!

**Comment by Khodour** [comment]
this bug reported in 2017 and now we are about to enter 2019 and still not yet fixed ! i have to fixe it by my self everytime i use pod update !!
