### ISSUE TITLE
Compiler not recognizing LoginButton after installing pod and importing framework

### ISSUE THREAD

**Issue by patrickridd** [facebook/facebook-sdk-swift#168]
I can't initialize the LoginButton. I've installed:
pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'

I then imported FacebookLogin, but still the compiler doesn't like it. Not sure if I'm missing a step here.

<img width="1680" alt="screen shot 2017-08-02 at 9 48 35 am" src="https://user-images.githubusercontent.com/6131413/28882350-32d1130c-7768-11e7-809e-d5c516c3a95d.png">

**Comment by codytwinton** [comment]
@patrickridd - I'm in process of closing old issues to help us focus on improving this SDK. If you're still running into this issue, please feel free to reopen this issue.
