### ISSUE TITLE
Fail to include to project by using "Carthage update"

### ISSUE THREAD

**Issue by yly813** [facebook/facebook-sdk-swift#17]
When running "Carthage update", the following is shown
`xcodebuild timed out while trying to read FBSDKIntegrationTests.xcodeproj 😭`

**Comment by nlutsenko** [comment]
Hey @yly813, this can happen sometimes due to a bug in carthage and xcodebuild.
Carthage has an explicit timeout set to avoid xcodebuild hanging sometimes.
I would recommend making sure you are running the latest Carthage, as well as general Xcode troubleshooting like removing your Xcode's Derived Data.

Let me know if you get any further, if not - would love to see your Cartfile and maybe a project that you can reproduce this with.

**Comment by yly813** [comment]
Hello @nlutsenko, thank you for the reply. I am still facing the same problem.

My carthage version is 0.16.2. Although I have checked the latest release is 0.17.2, mine one should be the available latest version by using `brew upgrade carthage`.
I have also tried `brew uninstall Carthage` then `brew install Carthage`, it turns out the provided version is still 0.16.2.

My Xcode version is 7.3.1 (7D1014).

My Cartfile,

```
github "Alamofire/Alamofire" ~> 3.4
github "Alamofire/AlamofireImage" ~> 2.0
github "realm/realm-cocoa"
github "kishikawakatsumi/KeychainAccess"
github "facebook/Facebook-SDK-Swift"
```

`Carthage update` is success without `github "facebook/Facebook-SDK-Swift"`

After `carthage update`,
![screen shot 2016-07-19 at 11 37 58 pm](https://cloud.githubusercontent.com/assets/5111418/16956589/9cd1fa64-4e0b-11e6-8dc4-349948b97d4b.png)

**Comment by nlutsenko** [comment]
Try running 'brew update' before 'brew upgrade carthage', as updating homebrew packages is a 2 step process (update the list of packages, then upgrade a package).

**Comment by yly813** [comment]
Hello @nlutsenko , thank you very much! It turns out to be my ignorance on using the `brew` command.
With the 2 step process, I can update my Carthage to version 0.17.2.
Using this latest version, the sdk could be use with `Carthage update`. My problem is tackled.

**Comment by nlutsenko** [comment]
Perfect! Glad I could help!
