### ISSUE TITLE
Login Dialog doesn't dismiss after returning from Facebook App in iOS 11

### ISSUE THREAD

**Issue by gbhall** [facebook/facebook-sdk-swift#172]
When selecting `Log In with the Facebook App` and completing the flow, upon return to the initiating app, the Login Dialog remains opened and is not automatically dismissed.

Works on devices prior to iOS 11.  

Initiated using the following:
```swift
let loginManager = LoginManager()
loginManager.logIn([ .publicProfile, .email ], viewController: self) { loginResult in
    switch loginResult {
    case .failed(let error):
        print(error)
    case .cancelled:
        print("User cancelled login.")
    case .success(let grantedPermissions, let declinedPermissions, let accessToken):
        print("Logged in!")
        print("grantedPermissions \(grantedPermissions) \n declinedPermissions \(declinedPermissions) \n accessToken \(accessToken)")
    }
}
```

More information: https://stackoverflow.com/questions/45577898/facebook-login-doesnt-doesnt-dismiss-login-dialog-after-login

**Comment by thisfiore** [comment]
Same issue with **Swift 3** on iOS 11 beta

**Comment by Nathan187** [comment]
glad and pissed off to see i'm not the only one with that problem

**Comment by vivatum** [comment]
It seems you have to fix AppDelegate. It helped me:

    func application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any) -> Bool {

        var signedIn: Bool = GIDSignIn.sharedInstance().handle(url, sourceApplication: sourceApplication, annotation: annotation)

        signedIn = signedIn ? signedIn : FBSDKApplicationDelegate.sharedInstance().application(application, open: url, sourceApplication: sourceApplication, annotation: annotation)

        return signedIn
    }

    @available(iOS 9.0, *)
    func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any]) -> Bool {

        var signedIn: Bool = GIDSignIn.sharedInstance().handle(url, sourceApplication: options[UIApplicationOpenURLOptionsKey.sourceApplication] as? String, annotation: options[UIApplicationOpenURLOptionsKey.annotation])

        signedIn = signedIn ? signedIn : FBSDKApplicationDelegate.sharedInstance().application(app, open: url, sourceApplication: options[UIApplicationOpenURLOptionsKey.sourceApplication] as? String, annotation: nil)

        return signedIn
    }

**Comment by nboyd-sportdx** [comment]
what is GIDSignIn???????????

**Comment by vivatum** [comment]
This is a GoogleSignIn method. You can skip it, if you use the FacebookSignIn procedure only. 

    func application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any) -> Bool {

        return FBSDKApplicationDelegate.sharedInstance().application(application, open: url, sourceApplication: sourceApplication, annotation: annotation)
    }

    @available(iOS 9.0, *)
    func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any]) -> Bool {

        return FBSDKApplicationDelegate.sharedInstance().application(app, open: url, sourceApplication: options[UIApplicationOpenURLOptionsKey.sourceApplication] as? String, annotation: nil)
    }

**Comment by nboyd-sportdx** [comment]
@vivatum thank you.  sorry for the sarcastic question....been a trying time working w/ this library

**Comment by gbhall** [comment]
Working as expected in `0.3.0`.

**Comment by jfeferman** [comment]
Please look at https://stackoverflow.com/questions/32299271/facebook-sdk-login-never-calls-back-my-application-on-ios-9 for a working solution.

**Comment by ThoseGuysInTown** [comment]
@vivatum Thank you!!! Idk why but when I checked the Facebook documentation it didn't mention having it in both app opens delegate. So thanks for clearing that up for me 😄
