### ISSUE TITLE
Caught signal triggered by the Swift runtime

### ISSUE THREAD

**Issue by reza355** [facebook/facebook-sdk-swift#174]
Hi i'm trying to install fbsdk swift with carthage, but it's seems fail and always show this error:

> Caught signal triggered by the Swift runtime!
Illegal instruction

> Unfortunately,  this is probably a bug in Swift and not Carthage. If
this is preventing you from doing work, please file an issue and we'll
do our best to work around it:
https://github.com/Carthage/Carthage/issues/new

> Please also consider filing a radar with Apple, containing the version
of Carthage and any crash report found in Console.app. 

anyone know how to solved this?

**Comment by etercode** [comment]
I experienced the same issue. Any ideas what to do?

**Comment by Maxismo** [comment]
Same here

**Comment by lindsaypond** [comment]
I'm also experiencing this issue.

**Comment by zirinisp** [comment]
Same here

**Comment by edopelawi** [comment]
Bump!

**Comment by MarcosMolero** [comment]
Same here

**Comment by reza355** [comment]
Up The Issue

**Comment by AndrewSB** [comment]
I just tested this and I didn't run into the error. If anyone is still running into it, please open a new issue!
