### ISSUE TITLE
Cocoapods integration with swift and Xcode 8.3.3 failed

### ISSUE THREAD

**Issue by Maxismo** [facebook/facebook-sdk-swift#176]
I create a brand new empty project and add only this in podfile. there is no such a framework called "FacebookShare" mention in [your document](https://developers.facebook.com/docs/swift/sharing/share-dialog). it can't even build.

this is how my podfile looks like:
platform :ios, '9.0'

target 'FBShare' do
  use_frameworks!

pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'

end

this is the error while building the workspace:
<img width="1125" alt="screen shot 2017-09-08 at 12 04 46 pm" src="https://user-images.githubusercontent.com/2225596/30195799-855d49da-9421-11e7-96d5-76697c485a89.png">

**Comment by nkhiem** [comment]
So I used xcode Version 8.3.3 (8E3004b)

**Comment by jasonwedepohl** [comment]
I have this issue as well.

**Comment by gfosco** [comment]
0.3.0 is now out, updated for Xcode9 and Swift4.  Assuming this issue is old, let us know if you have any further problems.
