### ISSUE TITLE
Why facebook is not maintaining this project!! 

### ISSUE THREAD

**Issue by bati668** [facebook/facebook-sdk-swift#179]
I can not use latest sdk with carthage!!

Please fix everything!
Please maintain!!!
What a fuck!!!!!!

@nlutsenko

**Comment by anhdiepmmk** [comment]
i have same problem

**Comment by txaiwieser** [comment]
+1

**Comment by bati668** [comment]
@nlutsenko
How progress???

**Comment by bati668** [comment]
@nlutsenko 
hey hey
Please fix everything!

Please work!!

**Comment by zirinisp** [comment]
+1

We are spending days just to integrate their sdk everytime iOS is changing. It should be ready before iOS 11 was officially released.

**Comment by scurioni** [comment]
+1

**Comment by imairi** [comment]
+1

**Comment by gaming-hacker** [comment]
+1

**Comment by mufumbo** [comment]
+1 what a headache..

**Comment by gfosco** [comment]
Coming soon, hopefully monday (no guarantee), a new build of the obj-c sdk and a full swift 4 update for the swift-sdk.  Hang in there, we're going to get this back to fully maintained.

**Comment by gfosco** [comment]
0.3.0 is hitting right now, thanks for your patience!

**Comment by ekimia** [comment]
thanks @gfosco!
