### ISSUE TITLE
Xcode 9 Fails to Build

### ISSUE THREAD

**Issue by martheli** [facebook/facebook-sdk-swift#181]
Just installed this project via cocoapods to my Xcode 9, Swift 4 project and am receiving the following build errors:

<img width="274" alt="screen shot 2017-09-20 at 7 48 16 pm" src="https://user-images.githubusercontent.com/20176169/30672818-b9b1f76a-9e3c-11e7-8bc7-43ea40a915a0.png">

**Comment by leogiertz** [comment]
@nlutsenko Would be great if you could look into this.

**Comment by ryana** [comment]
Also ran into this. Currently blocked on developing a new app in Xcode 9 GM. I tried to fix myself, but quickly got down into a rabbit hole.

**Comment by spromicky** [comment]
The solution depends on how you include FacebookSDK in to your project. If you manually add FacebookSDK in your workspace, then just change swift version in `Build Settings` like this:
<img width="438" alt="screen shot 2017-09-22 at 13 51 13" src="https://user-images.githubusercontent.com/3592457/30741410-540bd176-9f9d-11e7-9269-959bcdd05d0e.png">
For CocoaPods [this](https://gist.github.com/JohnSundell/519cb322978ac59f5ac161ff67e4413b) will resolve that issue.

**Comment by Daltron** [comment]
Please see my temporary solution posted in #182

**Comment by reddioment** [comment]
I collected all the errors and fixes and created this tutorial on [compileing the Swift SDK in Swift 4](http://www.kristofk.com/facebook-swift-sdk-updated-to-swift-4/)

**Comment by gfosco** [comment]
Coming soon, hopefully monday (no guarantee), a new build of the obj-c sdk and a full swift 4 update for the swift-sdk.  Hang in there.

**Comment by gfosco** [comment]
0.3.0 is hitting right now, thanks for your patience!
