### ISSUE TITLE
build failed in Xcode 9.0GM with Swift 4.0

### ISSUE THREAD

**Issue by YaoJuan** [facebook/facebook-sdk-swift#182]

**Comment by Daltron** [comment]
As a temporary workaround, if you are using cocoapods, you can do this:

1. Request specific versions in your Podfile. By default, installing the `FacebookCore` pod also installs the `FBSDKCoreKit` pod, and installing the `FacebookShare` pod also installs the `FBSDKShareKit` pod and so on and so on..

```ruby
pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'
pod 'FBSDKCoreKit', '~> 4.21.0'
pod 'FBSDKLoginKit', '~> 4.21.0'
pod 'FBSDKShareKit', '~> 4.21.0'
```
They key is pointing the `FBSDK` pods to the 4.21.0 version.

2. Telling your pod file to compile the Facebook pods into Swift 3.2 if your project is compiled in Swift 4

```ruby
post_install do |installer|
    installer.pods_project.targets.each do |target|
        facebook_pods = ['FacebookCore', 'FacebookLogin', 'FacebookShare']
        if facebook_pods.include? target.name
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.2'
            end
        end
    end
end
```
There is no need to include the `FBSDK` pods in the array to check for as they are written in Objective-C

**Comment by reddioment** [comment]
I collected all the errors and fixes and created this tutorial on [compileing the Swift SDK in Swift 4](http://www.kristofk.com/facebook-swift-sdk-updated-to-swift-4/)

**Comment by lawgimenez** [comment]
Is Facebook planning to update this SDK soon?

**Comment by wvdk** [comment]
You can use the other sdk instead. https://github.com/facebook/facebook-sdk-swift

````
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
````

It seems to be Swift 4 ready. :)

**Comment by reddioment** [comment]
@wvdk Yes you could use it, it's an older SDK that has been thoroughly tested, and it's the one Facebook recommends. However, I'd personally want to have as much of my codebase in Swift as possible which would be the point of this SDK as it does the exact same thing.

**Comment by gfosco** [comment]
Coming soon, hopefully monday (no guarantee), a new build of the obj-c sdk and a full swift 4 update for the swift-sdk.  Hang in there.

**Comment by foghel** [comment]
Hi, Any news regarding the swift4 Update ?
Thanks.

**Comment by claudiocamara** [comment]
There's a pull request already. 

https://github.com/facebook/facebook-sdk-swift/pull/184

**Comment by gfosco** [comment]
Just waiting on the hotfix for the obj-c SDK.

**Comment by rlinyard** [comment]
Is there any ETA for the hotfix? Like others, I would like to move forward with the Swift version of the SDK but am stuck in Swift 4 without this.

**Comment by gfosco** [comment]
0.3.0 has landed and the pod is being published, everything should be good to go momentarily!
