### ISSUE TITLE
Carthage fails to build

### ISSUE THREAD

**Issue by CocoaPriest** [facebook/facebook-sdk-swift#186]
`Carthage/Checkouts/Facebook-SDK-Swift/Sources/Core/UserProfile/UserProfile.PictureView.swift:22:8: error: no such module 'FBSDKCoreKit.FBSDKProfilePictureView'
import FBSDKCoreKit.FBSDKProfilePictureView`

Using latest 0.3.0

**Comment by gfosco** [comment]
Not able to reproduce, can you provide more information on your process?

**Comment by ekimia** [comment]
@CocoaPriest try clearing carthage's cache and try again using a standard `carthage update`, that worked for me.

**Comment by CocoaPriest** [comment]
@ekimia thanx, it helped
