### ISSUE TITLE
Ambiguous use of 'init'

### ISSUE THREAD

**Issue by kyle-s-autobrain** [facebook/facebook-sdk-swift#187]
var content = LinkShareContent(url: URL(string:"your share url")!)

Gives error no matter what I do. After looking into it, it seems it doesn't know which init function to use. I only see one init function inside LinkShareContent class.

Using cocoapods to install the framework. Using the latest version.

**Comment by hhelmric** [comment]
`        let myContent = LinkShareContent(url: URL(string: "https://itunes.apple.com/us/app/how-much-fun-question-game/id1237009705")!)
        let shareDialog = ShareDialog(content: myContent)
        shareDialog.mode = .native
        shareDialog.failsOnInvalidData = true
        shareDialog.completion = { result in
            // Handle share results
            
        }
        
        try! shareDialog.show()`


This is currently working for m. I force unwrapped the try, but you will probably want to do something else.

**Comment by kyle-s-autobrain** [comment]
I ended up deleting the other init function in LinkShareContent that is deprecated to fix my issue.
