### ISSUE TITLE
Carthage hangs on Bolts-ObjC

### ISSUE THREAD

**Issue by ThorinHanson** [facebook/facebook-sdk-swift#189]
I have been having issues trying to get the new framework built with Carthage, as it will hang on the fetching or cloning step of Bolts-ObjC.

I have deleted  the Carthage directory
I have deleted ~/Library/Caches/org.carthage.CarthageKit
I have deleted the Cartfile.resolved

Any ideas or help you could provide would be fantastic.  As an aside, why Bolts-ObjC instead of Bolts-Swift?

**Comment by gfosco** [comment]
This library depends on facebook-ios-sdk, the ObjC SDK, so that will depend on Bolts-ObjC.  

When you say hang, you mean it never continues / no error?

**Comment by ThorinHanson** [comment]
Ah, that makes sense.  Thanks for clearing it up.

Regarding the hang, yes.  It stops responding, never continues and never produces an error.  I thought perhaps it was trying different versions as described in https://github.com/Carthage/Carthage/issues/1219 and I have tried the resolution indicated in https://github.com/Carthage/Carthage/issues/1370.

**Comment by ThorinHanson** [comment]
Removed all other libraries in my cartfile and the sdk built.  Closing this as a non-issue.

**Comment by mark-r2r** [comment]
This is definitely still an issue. Deleting all other libraries isn't a fix.  Any ideas?
`carthage: 0.31.0`

```
*** Fetching Facebook-SDK-Swift
*** Fetching facebook-ios-sdk
*** Fetching Bolts-ObjC
*** Checking out Facebook-SDK-Swift at "61d849ef884304c4414d51b3dae3cb2b5a7ee1ef"
*** Checking out facebook-ios-sdk at "sdk-version-4.37.0"
*** Checking out Bolts-ObjC at "1.9.0"
```
