### ISSUE TITLE
Ambiguous use of 'init'

### ISSUE THREAD

**Issue by DelphiClaer** [facebook/facebook-sdk-swift#191]
Hi,

I have a similar problem like issue #187 but I can't work around it.

In XCode 9.0 and 9.1 it works perfectly but when I try to deploy with XCode 8.3.1 the code below gives the error "Ambiguous use of 'init' "

Both functions are in FacebookCore > AppEvent.Builtin.swift
FacebookCore is installed with CocoaPods and I'm using the latest version

``` 
public static func rated<T: UnsignedInteger>(contentType: String? = nil, contentId: String? = nil,  maxRatingValue: T? = nil, valueToSum: Double? = nil, extraParameters: ParametersDictionary = [:]) -> AppEvent {
    var parameters = extraParameters
    contentType.onSome({ parameters[.contentType] = $0 })
    contentId.onSome({ parameters[.contentId] = $0 })
    maxRatingValue.onSome({ parameters[.maxRatingValue] = NSNumber(value: UInt64($0)) }) // this is where the error shows
    return AppEvent(name: .rated, parameters: parameters, valueToSum: valueToSum)
  }
}
```

Same happens here
```
public static func initiatedCheckout<T: UnsignedInteger>(contentType: String? = nil, contentId: String? = nil, itemCount: T? = nil, paymentInfoAvailable: Bool? = nil, currency: String? = nil, valueToSum: Double? = nil, extraParameters: ParametersDictionary = [:]) -> AppEvent {
    var parameters = extraParameters
    contentType.onSome({ parameters[.contentType] = $0 })
    contentId.onSome({ parameters[.contentId] = $0 })
    itemCount.onSome({ parameters[.itemCount] = NSNumber(value: UInt64($0)) }) // this is where the same error is showing as well
    paymentInfoAvailable.onSome({
      parameters[.paymentInfoAvailable] = $0 ? FBSDKAppEventParameterValueYes : FBSDKAppEventParameterValueNo
    })
    currency.onSome({ parameters[.currency] = $0 })
    return AppEvent(name: .initiatedCheckout, parameters: parameters, valueToSum: valueToSum)
  }
}
```

Thank you

**Comment by kyle-s-autobrain** [comment]
I actually changed the code in the other issue. I probably should have been more specific. I found another issue where they changed those to lines of code. I reverted it to:
maxRatingValue.onSome({ parameters[.maxRatingValue] = NSNumber(value: $0.toUIntMax()) })

**Comment by cmcgheit** [comment]
@DelphiClaer, did you ever get it to work on 8.3.1?

I am having this issue when trying to use with Xcode 8.3.3:

It looks like it has the proper syntax as well `UInt64($0)`, like what was talked about in #162 , but I am still getting the error.

![screen shot 2017-12-20 at 10 44 00 am](https://user-images.githubusercontent.com/24944725/34218090-db5edeb4-e572-11e7-995b-2ee2dd7923a8.png)

Upgrading to 9.0 will help with this issue is what I'm gathering?

**Comment by DelphiClaer** [comment]
@cmcgheit I ended up downgrading everything back again to the previous version I was working with and have not tried updating since. Sorry I can't be of more help

**Comment by cmcgheit** [comment]
@DelphiClaer no problem, what version is that? I will try that as an alternative, I'm not ready to upgrade to Xcode 9 just yet.

**Comment by DelphiClaer** [comment]
@cmcgheit 
In my Podfile:
```
pod 'FacebookCore', '~> 0.2.0'
pod 'FacebookLogin', '~> 0.2.0'
```

**Comment by jeromeheaven** [comment]
@DelphiClaer you just saved my life. Thanks for the quick fix!
