### ISSUE TITLE
Issue with facebook sdk while compiling code with XCode

### ISSUE THREAD

**Issue by PoorvaSingh09** [facebook/facebook-sdk-swift#194]
Pods/FacebookCore/Sources/Core/AppEvents/AppEvent.Builtin.swift:125:75: ambiguous use of 'init'
maxRatingValue.onSome({ parameters[.maxRatingValue] = NSNumber(value: UInt64($0)) })
 ^
/FacebookCore/Sources/Core/AppEvents/AppEvent.Builtin.swift:239:65: ambiguous use of 'init'
itemCount.onSome({ parameters[.itemCount] = NSNumber(value: UInt64($0)) })
^

**Comment by PoorvaSingh09** [comment]
Circle CI fails after installing pod

**Comment by lostatseajoshua** [comment]
@PoorvaSingh09 are you still facing this issue? Can you provide more context on this? (Xcode version, Swift version) Thank you.

**Comment by codytwinton** [comment]
@PoorvaSingh09 - I'm in process of closing old issues to help us focus on improving this SDK. If you're still running into this issue, please feel free to reopen this issue.
