### ISSUE TITLE
FBSDKAccessToken.current() has hidden force unwrap 

### ISSUE THREAD

**Issue by romaHerman** [facebook/facebook-sdk-swift#195]
My app was crashing on following line FBSDKAccessToken.current().hasGranted("publish_actions")
I can assume that there is force unwrapping somewhere inside because 

` if let currentToken = FBSDKAccessToken.current() ` did the trick 

If it's possible will be better to return optional value , to imply that there might be nil 
Thanks in advance !

**Comment by lostatseajoshua** [comment]
Closing as the current token is optional now.
https://github.com/facebook/facebook-sdk-swift/blob/82d4f4bc4226bd9d0494a604cb2f39632f6a0b57/Sources/Core/Common/AccessToken.swift#L89
