### ISSUE TITLE
shareDialog thumbnail picture missing

### ISSUE THREAD

**Issue by synergetica11** [facebook/facebook-sdk-swift#196]
Hi! I am trying to use this SDK to share a link by shareDialog, but I find that the thumbnail picture which is passed by "imageURL" is missing.

```
let content = LinkShareContent(url: NSURL(string: self.imageUrl) as URL!, title: "test title", description: "test description", imageURL: NSURL(string: self.imageUrl) as URL!)
let shareDialog = ShareDialog(content: content)
        
shareDialog.mode = .feedBrowser
shareDialog.failsOnInvalidData = true
shareDialog.completion = { result in
        print(result)
}
 do {
      try shareDialog.show()
}catch {
      print("error!!!")
}
```

I read the similar closed issue but that solution doesn't work for me. I tried to change image resolution. How can I share the link and thumbnail?  Thank you for the response!

**Comment by codytwinton** [comment]
@synergetica11 - I'm in process of closing old issues to help us focus on improving this SDK. If you're still running into this issue, please feel free to reopen this issue.
