### ISSUE TITLE
Is this repo going to be deprecated by Feb 5th, 2018?

### ISSUE THREAD

**Issue by AshleyDeng** [facebook/facebook-sdk-swift#197]
[Swift SDK](https://developers.facebook.com/docs/swift/login) says it will become deprecated by  Feb 5th, 2018 and we should be using [4.28.0](https://developers.facebook.com/quickstarts/?platform=ios)

However, the 4.28.0 still uses Objective-C code. Is Facebook NOT going to support swift at all?

**Comment by gaming-hacker** [comment]
i think this has already been abandoned by fb, there hasn't been any replies or answers to any questions in months.

**Comment by lostatseajoshua** [comment]
The repo is not deprecated.

**Comment by MingyaoLiu** [comment]
Nice response time!
