### ISSUE TITLE
facebook-sdk crash on Graph Request

### ISSUE THREAD

**Issue by sheinix** [facebook/facebook-sdk-swift#199]
I'm getting this crash report of Crashlytics for some users when they try to login with their Facebook Account on our iOS app `empty-list HTTPURLResponse? first-element-marker GraphRequestResult empty-list`

I'm get the userToken correctly, but for some users (regardless of the iOS version) the app crashes with the error.  From my Podfile.lock:

 - **FacebookCore (0.3.0):**
    - Bolts (~> 1.8)
    - FBSDKCoreKit (~> 4.27)
  - **FacebookLogin (0.3.0):**
    - Bolts (~> 1.8)
    - FacebookCore (~> 0.3)
    - FBSDKCoreKit (~> 4.27)
    - FBSDKLoginKit (~> 4.27)
  - **FBSDKCoreKit (4.27.1):**
    - Bolts (~> 1.7)
  - **FBSDKLoginKit (4.27.1):**
    - FBSDKCoreKit

Here's my code:

```
let graphRequest: GraphRequest = GraphRequest(graphPath: "me", parameters: ["fields":"first_name,email, picture.type(large)"])
            graphRequest.start({ (response, graphResult) in
                switch graphResult {
                case .success(let graph):
                    if let dict = graph.dictionaryValue {
                        let loginUser = LoginUser(email: dict["email"] as! String,
                                                  password: MascoterosApi.loginFBAutoGenPassword.password,
                                                  socialLoginToken: token,
                                                  loginType: LoginTypes.facebook)
                        observer.onNext(loginUser)
                        observer.onCompleted()
                    } else {
                        observer.onError(APIValidationErrors.facebook_login_error)
                        observer.onCompleted()
                    }
                case .failed:
                    observer.onError(MAValidationErrors.facebook_login_error)
                    observer.onCompleted()
                }
        })
```

**Comment by sheinix** [comment]
Adding on this, the graph request is not returning the "email" parameter even when it was accepted.

**Comment by maynardewm** [comment]
Also having this problem

**Comment by MrOverflOOw** [comment]
Same problem here

**Comment by xhidnoda** [comment]
Same Problem here.
"The graph request is not returning the "email" parameter even when it was accepted" on iOS 11 XCode 9.2 and swift 4.

**Comment by codytwinton** [comment]
@sheinix - I'm in process of closing old issues to help us focus on improving this SDK. If you're still running into this issue, please feel free to reopen this issue.
