### ISSUE TITLE
Facebook login using LoginManager doesn't open Facebook native app

### ISSUE THREAD

**Issue by reysayas** [facebook/facebook-sdk-swift#204]
I can't use the facebook app as login. I've tried everything still open on safari. Not sure if it is a bug on swift or am I missing something? Thank you!

![screen shot 2017-11-29 at 9 55 34 pm](https://user-images.githubusercontent.com/19600418/33378534-18898f7e-d550-11e7-9a60-3b9caadca883.png)

![screen shot 2017-11-29 at 9 55 43 pm](https://user-images.githubusercontent.com/19600418/33378542-1dd10598-d550-11e7-9c89-d09e5c0a0d6e.png)

![screen shot 2017-11-29 at 9 55 48 pm](https://user-images.githubusercontent.com/19600418/33378553-212f25a8-d550-11e7-8fe7-c2e130d80dd9.png)

![screen shot 2017-11-29 at 9 57 20 pm](https://user-images.githubusercontent.com/19600418/33378690-92f734c8-d550-11e7-8f8b-39c01d901b84.jpg)

**Comment by seubseub** [comment]
me too. same happened

**Comment by seubseub** [comment]
@reysayas See this https://developers.facebook.com/bugs/141267893132714/?hc_location=ufi :)

**Comment by reysayas** [comment]
@seubseub - this is different problem.. The app itself only use safari for login and not the facebook app

**Comment by seubseub** [comment]
@reysayas ok this above problem is my problem. I hope your problem is solved.

**Comment by reysayas** [comment]
@seubseub its ok.. If you found any solution please share it to me while we wait for response from the team

**Comment by seubseub** [comment]
@reysayas ok If i find any solution, i will share it to you. good luck :)

**Comment by mdflores** [comment]
same here. Following this issue

**Comment by mdflores** [comment]
I've been diving to this issue quite a while now. and found this article from Facebook 2 years ago, that they are leveraging the Safari App since it has higher Clicks over the App. I think this explains everything.

> We've been monitoring data and CTRs for over 250 apps over the last 6 weeks since iOS 9 launched. The click-through rate (CTR) of SVC Login outperforms the CTR of app-switch Login and is improving at 3x the rate of the app-switch experience. This indicates that the SVC experience is better for people and developers today, and will likely be the best solution in the long run. For this reason, the latest Facebook SDK for iOS uses SVC as the default experience for Login.

https://developers.facebook.com/blog/post/2015/10/29/Facebook-Login-iOS9/

**Comment by n13** [comment]
^^^^ 
Ok, that's a pretty extensive treatise on the topic. I'd been wondering why and I thought it was a bug of some kind. Turns out, not.

This is not a bug, should be closed.

**Comment by codytwinton** [comment]
@n13 - Thanks for the thoughts on this issue!

@reysayas - I'm in process of closing old issues to help us focus on improving this SDK. If you're still running into this issue, please feel free to reopen this issue.

**Comment by MarchTs** [comment]
pod 4.39.0 can't open native app. so try to down version to 4.38.1 work for me!
