### ISSUE TITLE
SMS Authentication Completed via AccountKit. But Any Delegates Not Getting Called. (in Swift 4)

### ISSUE THREAD

**Issue by dyyeom** [facebook/facebook-sdk-swift#210]
Via the function of "AKFAccountKit:viewControllerForPhoneLogin()", a view controller was generated. It comes up without any issue and I get the SMS message without any issue. After I responded to the message, I was told that the SMS authentication was successful.

But none of the four delegates that I had previously set up were called up.

There is not any issue with delegate setups.

**Comment by tvillafane** [comment]
@dyyeom I had this same problem, I found a fix, use the following:` func viewController(_ viewController: (UIViewController & AKFViewController)!, didCompleteLoginWithAuthorizationCode code: String!, state: String!) {
        print("this works")
    }`

instead of: ` private func viewController(viewController: UIViewController!, didCompleteLoginWithAuthorizationCode code: String!, state: String!) { print("this doesn't work") }`

**Comment by codytwinton** [comment]
@dyyeom - I'm in process of closing old issues to help us focus on improving this SDK. If you're still running into this issue, please feel free to reopen this issue.

**Comment by smkdoss73** [comment]
yes am also facing this issues 

`  let inputState: String = UUID().uuidString
        let viewController:AKFViewController = accountKit.viewControllerForPhoneLogin(with: nil, state: inputState)  as AKFViewController
        viewController.delegate = self
        viewController.enableSendToFacebook = true
        self.prepareLoginViewController(viewController)
        self.present(viewController as! UIViewController, animated: true, completion: nil)`


`extension LoginViewController: AKFViewControllerDelegate{

   private func viewController(_ viewController: UIViewController!, didCompleteLoginWith accessToken: AKFAccessToken!, state: String!) {
        print("Login success with AccessToken")

    }
    func viewController(_ viewController: UIViewController!, didCompleteLoginWithAuthorizationCode code: String!, state: String!) {
        print("Login succcess with AuthorizationCode")
    }
    private func viewController(_ viewController: UIViewController!, didFailWithError error: NSError!) {
        print("We have an error \(error)")
    }
    func viewControllerDidCancel(_ viewController: UIViewController!) {
        print("The user cancel the login")
    }
    
    func prepareLoginViewController(_ loginViewController: AKFViewController) {
        
        loginViewController.delegate = self
        loginViewController.enableSendToFacebook = true
        loginViewController.advancedUIManager = nil

        //Costumize the theme
        let theme:AKFTheme = AKFTheme.default()
        theme.headerBackgroundColor = UIColor(red: 0.325, green: 0.557, blue: 1, alpha: 1)
        theme.headerTextColor = UIColor(red: 1, green: 1, blue: 1, alpha: 1)
        theme.iconColor = UIColor(red: 0.325, green: 0.557, blue: 1, alpha: 1)
        theme.inputTextColor = UIColor(white: 0.4, alpha: 1.0)
        theme.statusBarStyle = .default
        theme.textColor = UIColor(white: 0.3, alpha: 1.0)
        theme.titleColor = UIColor(red: 0.247, green: 0.247, blue: 0.247, alpha: 1)
        loginViewController.theme = theme
        
    }
}
`

**Comment by ioshitendra** [comment]
i am solve this issue please  erase old code add this code.
extension WalkthroughVC: AKFViewControllerDelegate {
    
    func viewController(_ viewController: UIViewController!, didCompleteLoginWithAuthorizationCode code: String!, state: String!) {
        ////Print("did complete login with AuthCode \(code) state \(state)")
    }
    
    func viewController(_ viewController: UIViewController!, didFailWithError error: Error!) {
        ////Print("error \(error)")
    }
    
    func viewController(_ viewController: UIViewController!, didCompleteLoginWith accessToken: AKFAccessToken!, state: String!) {
        _accountKit?.requestAccount({ (account, error) in
            
        
            if error == nil {
//                let categoryVC = CategorySelectionVC.instantiateFromXIB() as CategorySelectionVC
//                categoryVC.mobileNum = account?.phoneNumber?.phoneNumber
//                self.navigationController?.pushViewController(categoryVC, animated: true)
                  self.mobileNum = account?.phoneNumber?.phoneNumber
                  self.callMobileRegistrationAPI()
                
            }else{
                ////Print("error")
            }
        })
    }
    
    func viewControllerDidCancel(_ viewController: UIViewController!) {
        
    }
  
    private func callMobileRegistrationAPI() {
        SVProgressHUD.show()
        
        let strDeviceToken = UserDefaults.standard.string(forKey: "device_Token")
        let params: DictType = ["device_type": "IOS",
                                "device_token": strDeviceToken ?? UIDevice.current.identifierForVendor!.uuidString,
                                "device_id": strDeviceToken ?? UIDevice.current.identifierForVendor!.uuidString,
                                "categories_ids":"",
                                "phone_number": mobileNum as Any
        ]
        //print(params)

        APIManager().postRequest(withParams: params, url: URLContants.registerMobile, authReq: false, langReq: true, completion: { [unowned self] (JSON: Any?, response: URLResponse?, error: Error?) in

            if let dict = JSON as? DictType {
                //print(dict)
                guard let metaInfo = dict["meta"] as? DictType else {
                    SVProgressHUD.dismiss()
                    if dict["message"] != nil  {
                        self.showAlert(title: "", message: dict["message"] as? String)
                    }
                    return
                }
                if (metaInfo["status"] as? Bool)! == true {
                    //Save the user details for auto login
                    self.saveUserDetails(details: (dict["data"] as? DictType)!)
                    let userData = dict["data"] as? DictType
                    SDWebImageManager.shared().imageDownloader?.downloadImage(with: URL.init(string: (userData?["profile_image"] as? String)!), options: .continueInBackground, progress: { (receivedSize, ExpectedSize, imageURL) in
                        ////Print(receivedSize)
                    }, completed: { (image, theData, error, status) in
                        // your function here
                        let _ = image?.saveImageToDocumentDirectory("TetootaUserProfile", fileName: "ProfileImage")
                    })

                    let tempAry = (dict["data"] as! NSDictionary).value(forKey: "categories") as! NSArray
                    let loginDict = dict["data"] as! NSDictionary
                    let kUserDefault = UserDefaults.standard
                    kUserDefault.set(String(describing: loginDict["all_notification"]!), forKey: "AllNotificationOn")
                    kUserDefault.set(String(describing: loginDict["chat_notification"]!), forKey: "ChatNotificationOn")
                    kUserDefault.set(String(describing: loginDict["proposal_notification"]!), forKey: "ProposalNotificationOn")
                    kUserDefault.set(String(describing: loginDict["is_visible"]!), forKey: "VisibleSettingOn")
                    kUserDefault.set(loginDict["referralCode"], forKey: "TetootaReferralCode")
                    kUserDefault.synchronize()
                    let tempDict:NSDictionary = ["meta":["code":200,
                                                         "message":"Listing done", "status":NSNumber(value: 1)], "data": tempAry]
                    let mDictCategory = NSMutableDictionary(dictionary: tempDict)
                    UserDefaults.standard.set(mDictCategory, forKey: "SelectedCategory")

                    let hostVC = HostViewController.instantiateFromXIB() as HostViewController
                    self.navigationController?.pushViewController(hostVC, animated: true)
                   
                }else {
                    if metaInfo["message"] != nil  {
                        SVProgressHUD.dismiss()
                        self.showAlert(title: "", message: metaInfo["message"] as? String)
                    }
                }
            }
        })
    }
    
}
