### ISSUE TITLE
Semantic Issues and Compiler Warnings

### ISSUE THREAD

**Issue by CalumJB** [facebook/facebook-sdk-swift#211]
I have installed the latest version of the Facebook SDK for Swift (pod 'FacebookCore', pod 'FacebookLogin', pod 'FacebookShare') using the latest version on cocoapods (28/12/2017). Running Xcode 9.2 there are several issues shown when building an application. I have attached screenshot for your convenience.

<img width="267" alt="screen shot 2017-12-28 at 18 51 10" src="https://user-images.githubusercontent.com/34747947/34420310-cfea34a4-ec00-11e7-9634-36b08956f8c1.png">
<img width="268" alt="screen shot 2017-12-28 at 18 51 23" src="https://user-images.githubusercontent.com/34747947/34420311-d1009644-ec00-11e7-9af0-4add4750464e.png">
<img width="268" alt="screen shot 2017-12-28 at 18 51 34" src="https://user-images.githubusercontent.com/34747947/34420313-d2a95e68-ec00-11e7-8b5e-0302a0732422.png">
<img width="265" alt="screen shot 2017-12-28 at 18 51 46" src="https://user-images.githubusercontent.com/34747947/34420316-d447fa72-ec00-11e7-978d-bdbb2abd98c0.png">
<img width="268" alt="screen shot 2017-12-28 at 18 51 53" src="https://user-images.githubusercontent.com/34747947/34420318-d5ca7974-ec00-11e7-92f8-c7af0e0f2447.png">

**Comment by lawrence-edmondson** [comment]
What version of Swift are you running? It appears you're running version 4. If so, I would ignore these warnings because the Facebook SDK hasn't been rewritten in Swift version 4 as yet.
