### ISSUE TITLE
Cannot install Facebook SDK using Carthage with submodules

### ISSUE THREAD

**Issue by zcsipler** [facebook/facebook-sdk-swift#212]
I am trying to install facebook swift sdk with carthage, using submodules.  This is due to our special project structure.

I am using "carthage update --use-submodules --no-build" and I got this error:

*** Fetching facebook-sdk-swift
*** Fetching facebook-ios-sdk
*** Fetching Bolts-ObjC
*** Checking out Bolts-ObjC at "1.9.0"
*** Checking out facebook-ios-sdk at "sdk-version-4.29.0"
*** Checking out facebook-sdk-swift at "0.3.0"
A shell task (/usr/bin/env git submodule --quiet sync --recursive (launched in /Users/csiplerzoltan/DT.Projects/testFBApp)) failed with exit code 128:
fatal: Not a git repository (or any of the parent directories): .git

Reproducible on this test project:
https://github.com/zcsipler/testFBApp.git

**Comment by AndrewSB** [comment]
@zcsipler this looks like it's an issue with the Objective-C framework. So it'll have to be fixed at https://github.com/facebook/facebook-ios-sdk
