### ISSUE TITLE
Crash ios 11.2 SDK version 0.3.0 installed by cocoapods

### ISSUE THREAD

**Issue by GuillermoIHS** [facebook/facebook-sdk-swift#217]
I have the next crash only on 11.2 iOS version:

[FBSDKAppEventsState extractReceiptData]: unrecognized selector sent to instance

**Comment by dsb92** [comment]
I'm experiencing this too. Happens when you track something and go the background and then come back.

**Comment by codytwinton** [comment]
@GuillermoIHS - I'm in process of closing old issues to help us focus on improving this SDK. If you're still running into this issue, please feel free to reopen this issue.
