### ISSUE TITLE
framework not found FBSDKShareKit for architecture arm64

### ISSUE THREAD

**Issue by Lazare62** [facebook/facebook-sdk-swift#219]
Xcode doesn't found the framework FBSDKSharekit when i build.

![capture d ecran 2018-02-27 a 11 56 03](https://user-images.githubusercontent.com/26254215/36725118-8a4b7464-1bb5-11e8-83fc-5503446a4276.png)
I already have a configuration for Firebase Authentication (Use of FBSKCoreKit, FBSDKLoginKit, Bolt). 
And I just need the FBSDKShareKit.
I follow all the installation process for Carthage, but it not working.

![capture d ecran 2018-02-27 a 11 54 42](https://user-images.githubusercontent.com/26254215/36725115-8a1f28f0-1bb5-11e8-8ba0-609a2a2539b6.png)
![capture d ecran 2018-02-27 a 11 55 17](https://user-images.githubusercontent.com/26254215/36725117-8a372b80-1bb5-11e8-9302-e84628fa8e84.png)

And the search path is configured.
![capture d ecran 2018-02-27 a 12 05 33](https://user-images.githubusercontent.com/26254215/36725440-9ac11686-1bb6-11e8-85e8-970938c70594.png)

Xcode run on 9.2 version and Swift 3

**Comment by codytwinton** [comment]
@Lazare62 - I'm in process of closing old issues to help us focus on improving this SDK. If you're still running into this issue, please feel free to reopen this issue.
