### ISSUE TITLE
Display name not working

### ISSUE THREAD

**Issue by vignesh-s** [facebook/facebook-sdk-swift#221]
When the user clicks the facebook login button, the below pop up will come.

<img src="https://user-images.githubusercontent.com/13272208/37659365-c6647754-2c75-11e8-8ed3-38ade62142ea.png" width="200"/>

This using the project name instead of the app's display name or the Facebook display name.

I have tried setting
 - `FacebookDisplayName` in `info.plist`
 - `SDKSettings.displayName`

I can't find these `displayName` anywhere in entire login flow.
After the popup, in all the places I can see only the app name given on facebook developer site.
Kindly use the app display name or `FacebookDisplayName` atleast in the popup
We cannot change the name of the project for some reasons & I hope lots of persons may face this issue in some cases.

**Comment by Lopdo** [comment]
This isn't facebook issue. Popup is opened by Safari, so it's Apple who needs to fix it. I don't expect it to be done anytime soon

**Comment by RubyWu39** [comment]
I had the same issue few days ago and solved it by changing the bundle name.

**Comment by codytwinton** [comment]
@vignesh-s - I'm in process of closing old issues to help us focus on improving this SDK. If you're still running into this issue, please feel free to reopen this issue.

**Comment by vignesh-s** [comment]
@codytwinton I am still having this issue, But I don't have access to reopen this issue since I am not a collaborator of this repo.
Can you itself kindly reopen it?

**Comment by codytwinton** [comment]
@vignesh-s Done, and thank you for the heads up! We're working on giving this SDK some much needed attention, so stay tuned. Also, in the meantime, if you find a fix, please feel free to submit a pull request.

**Comment by codytwinton** [comment]
Also, I do know that this popup is related to [`SFAuthenticationSession`](https://developer.apple.com/documentation/safariservices/sfauthenticationsession). You might find your solution associated with that class type.

**Comment by codytwinton** [comment]
@Lopdo Fair assessment. Closing for now.

**Comment by terasupernova** [comment]
Hi @vignesh-s i faced this issue also. You can just go to your project target > info > custom ios target properties > look for bundle name
Just change the bundle name to the name you want. My bundle name is $(PRODUCT_NAME) but not sure why the $(PRODUCT_NAME) will show the bundle id, so i change $(PRODUCT_NAME) to the name i want, then is work. You can try this.

**Comment by Dharm045** [comment]
Working like charm, Great help. Thanks

**Comment by avinashamanjha251** [comment]
thanks, work for me

**Comment by lautapercuspain** [comment]
@terasupernova Great answer. Thank you, keep it up!

**Comment by Lopdo** [comment]
@dachev that popup is under Apple control, they are asking if they can hand over control over to safari with your info, so it is logical it appears before new screen is opened. It is mentioned somewhere in apple documentation as well. This is something Apple needs to address, ideally by providing us with a field in plist file where we can enter string that would display there (or they could use app name instead of bundle identifier)

**Comment by dachev** [comment]
Thanks @Lopdo! Out of curiosity, which iOS framework is this functionality using?

**Comment by robtimp** [comment]
@dachev This uses SFAuthenticationSession with iOS 11, and ASWebAuthenticationSession with iOS 12
