### ISSUE TITLE
LoginButton SDK overrides frame set in initializer in layoutSubviews

### ISSUE THREAD

**Issue by Spilly** [facebook/facebook-sdk-swift#224]
When I set a frame when initializing the LoginButton it saves the frame and then adds the subview to the FBSDKLoginButton parent. Unfortunately then in the LoginButton's override of layoutSubviews it then goes on to set the frame of the sdkLoginButton to origin zero. This causes the button to not respect the frame passed in.

**Comment by codytwinton** [comment]
@Spilly - I'm in process of closing old issues to help us focus on improving this SDK. If you're still running into this issue, please feel free to reopen this issue.
