### ISSUE TITLE
Login using Facebook App

### ISSUE THREAD

**Issue by leandersantosm** [facebook/facebook-sdk-swift#229]
Hi, I'm trying to integrate FB login with FBSDK in my app, but the login method that shows is using Safari, where the user types his email and passwod. I've already tried to change the loginBehavior, but still the same.

How can I fix this?

**Comment by codytwinton** [comment]
@leandersantosm - I'm in process of closing old issues to help us focus on improving this SDK. If you're still running into this issue, please feel free to reopen this issue.
