### ISSUE TITLE
180 warnings on buildtime (Swift 4)

### ISSUE THREAD

**Issue by mazmik25** [facebook/facebook-sdk-swift#230]
Hey guys, i'm currently using swift 4, xcode 9, and ios 11 (if it is necessary)

I've followed the setup documentation. Actually it works very well, but there's something that bother me. When i try to build my apps, it turns like this

![screen shot 2018-05-19 at 9 19 07 am](https://user-images.githubusercontent.com/25825451/40264026-cd27ade6-5b45-11e8-92ea-7483fbb7fffd.png)

That warnings include from **Bolts**, **FBSDKCoreKit**, **FacebookCore**, **FBSDKLoginKit**, **FacebookLogin**, and **FacebookShare**. Is there anything i can do to fix this?

**Comment by kervich** [comment]
Would be helpful to know what are these exactly before giving you any advice. A link to your build log could help )

**Comment by mazmik25** [comment]
@kervich right now, i'm trying to login using **FBSDKLoginKit**, but after i build my project, the result will be like the images. i actually just want to remove the warning. 

Here are some of the warnings:
![screen shot 2018-05-21 at 11 17 15 am](https://user-images.githubusercontent.com/25825451/40290655-a71dda1c-5ce9-11e8-87b5-045c63bf521e.png)
![screen shot 2018-05-21 at 11 17 36 am](https://user-images.githubusercontent.com/25825451/40290660-af314f0e-5ce9-11e8-8d3e-be8e382081d7.png)
![screen shot 2018-05-21 at 11 22 47 am](https://user-images.githubusercontent.com/25825451/40290667-c0445412-5ce9-11e8-8f38-3d41a1d09090.png)

**Comment by mazmik25** [comment]
@kervich is it safe to fix the problem by just going through the code?

**Comment by kervich** [comment]
@mazmik25 seems like these dependencies are fixed in submodules. You can definitely apply autofixes if you build with Carthage, cocoaheads will overwrite your changes. Or you can fix the sources, check that all tests pass and everything works and then make PRs with the fixes in respective repositories. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mazmik25** [comment]
thanks for you help!
