### ISSUE TITLE
Update for ReadPermissions 

### ISSUE THREAD

**Issue by SirWellington** [facebook/facebook-sdk-swift#232]
You can no longer get a user's gender as part of their `public_profile.` Facebook changed their APIs so that you have to request a specific permission to request the `user_gender` permission to get it. 

The problem is that the Swift SDK does not have this option in the Swift enum. How can we request this new permission?

**Comment by SirWellington** [comment]
Ooops, I just noticed there is a `.custom` option which takes a string. Great foresight!

**Comment by codytwinton** [comment]
@SirWellington - I'm in process of closing old issues to help us focus on improving this SDK. If you're still running into this issue, please feel free to reopen this issue.

**Comment by ryomaDsakamoto** [comment]
@codytwinton  - I just wondering, is it possible to refer user`s gender and get it??
I`m not pretty sure how to use "ReadPermission.custom(String)" is solution for @SirWellington ??

**Comment by SirWellington** [comment]
@ryomaDsakamoto Since I have posted this issue, I believe they have added the `.userGender` permission natively, so you don't need to use the `custom` anymore. If you did wanna use the custom route, this is what you would do:

```swift
let permissions: [ReadPermission] = [ .email,  .custom("userGender") ]
```
