### ISSUE TITLE
Compiler error in Xcode 10 beta 1

### ISSUE THREAD

**Issue by kdawgwilk** [facebook/facebook-sdk-swift#235]
Line 151 has this compiler error: `Argument type 'SDKLoggingBehavior?' does not conform to expected type 'Sequence'`

Which might be a Swift 4.2 bug since `.loggingBehavior()` is a `NSSet` so maybe the bridging is failing?

https://github.com/facebook/facebook-sdk-swift/blob/baea2e1c5e453a5c627c7452f1c0f4d119ab365e/Sources/Core/Common/SDKSettings.swift#L143-L157

**Comment by catjia1011** [comment]
`flatMap` should be changed to `compactMap` in this case, which should already be done in Swift 4.1

**Comment by ChrisGriffiths** [comment]
#238

**Comment by kdawgwilk** [comment]
I would point out this is compiling with the 4.2 compiler but using 4.0 mode so it should be backwards compatible

**Comment by akshya672222** [comment]
Not working in Xcode 10 beta 2

**Comment by ManuelPoq** [comment]
this is still not working and neither is this solution https://stackoverflow.com/questions/50724936/xcode-10-fbsdk-sdkloggingbehavior

**Comment by ManuelPoq** [comment]
@akshya672222  Make sure that the FacebookCore pod has a `SWIFT_VERSION` of 4.2 in the build settings in your project

**Comment by akshya672222** [comment]
<img width="318" alt="screen shot 2018-07-05 at 8 45 35 pm" src="https://user-images.githubusercontent.com/1900605/42354377-68b4d3ce-8094-11e8-8091-47981814f16c.png">
Changed the swift_version, now getting this error @ManuelPoq

**Comment by akshya672222** [comment]
@ManuelPoq making it 4.1 worked, giving the error in 4.2

**Comment by ManuelPoq** [comment]
@akshya672222 yes sorry, it should be 4.1 :) Glad to hear that it worked 👍

**Comment by Jignesh1805** [comment]
compactMap not run in swift 4.0

**Comment by CHardaker** [comment]
Not compiling using xCode 10 release version using Swift 4.2. There are also some "always fails" messages which will make functions useless.

**Comment by Jignesh1805** [comment]
ok thank you.
how to solve in below issue 
I am uploaded video in facebook but not return post_id  ?

**Comment by kjoe07** [comment]
xcode 10 GM does not have swift4.1 to select as swift version just swift4.0 4.2 and swift3

**Comment by ANADIR** [comment]
> e in below issue
> I am uploaded

rraq
