### ISSUE TITLE
Carthage update fails on "FBSDKIntegrationTests"

### ISSUE THREAD

**Issue by hixfield** [facebook/facebook-sdk-swift#244]
I am running xCode 9.4.2 and Carthage 30.1, Carthage update fails:

*** Building scheme "FBSDKCoreKit-Dynamic" in FacebookSDK.xcworkspace
*** Building scheme "FBSDKCoreKit-Universal" in FacebookSDK.xcworkspace
*** Building scheme "FBSDKLoginKit-Dynamic" in FacebookSDK.xcworkspace
*** Building scheme "FBSDKIntegrationTests" in FacebookSDK.xcworkspace
Build Failed
	Task failed with exit code 66:
	/usr/bin/xcrun xcodebuild -workspace /Users/Geert/Documents/Git/snookercoach/Carthage/Checkouts/facebook-ios-sdk/FacebookSDK.xcworkspace -scheme FBSDKIntegrationTests -configuration Release -derivedDataPath /Users/Geert/Library/Caches/org.carthage.CarthageKit/DerivedData/9.4.1_9F2000/facebook-ios-sdk/sdk-version-4.34.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/p9/1bchlcmd6fd2l_n213lr3_0c0000gn/T/facebook-ios-sdk SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/Geert/Documents/Git/snookercoach/Carthage/Checkouts/facebook-ios-sdk)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/p9/1bchlcmd6fd2l_n213lr3_0c0000gn/T/carthage-xcodebuild.tZvi48.log

**Comment by NikKovIos** [comment]
Opened an issue https://developers.facebook.com/bugs/244450549671110/?legacy_version=true

**Comment by chuganzy** [comment]
This is Carthage side issue. Here is an open PR.
https://github.com/Carthage/Carthage/pull/2507

**Comment by codytwinton** [comment]
As @NikKovIos pointed out, this issue can be resolved by using a prior version of Carthage. Closing for now.

Please comment below if you think this issue needs to be re-opened.

**Comment by TheAbstractDev** [comment]
Is the problem fixed with _facebook-swift-sdk 0.5.0_ & _Carthage 0.31.2_ ?

**Comment by chuganzy** [comment]
@TheAbstractDev Yes, it should be
