### ISSUE TITLE
Make LoginButton be a subclass of UIButton and work nicely in Interface Builder

### ISSUE THREAD

**Issue by themythIOS** [facebook/facebook-sdk-swift#25]
Hi how can i load Facebook Login Button to my UIButton.. before i just change the UIButton class to FBSDKLoginButton... is it the same in swift or its pending? i tried my own customise UIButton view but its a mess with my Layout so , changing class for me is better. Maybe you could give me just a small solution. Adding to subview has a problem on width and height with layout frames in my UI.

**Comment by nlutsenko** [comment]
It's quite the same, though it's a subclass of UIView and not a UIButton. The new class name is `FacebookLogin.LoginButton` or in other words - FacebookLogin.framework contains`LoginButton` that you can use.

You can still try to just change the class, but few things might not work.
Let me know how it goes and if you run into any issues.

**Comment by themythIOS** [comment]
Thanks for the reply.. What i was trying to say is that on Xcode when you go to the UIButton and click Identity Inspector>Custom Class>  before we put FBSDKLoginButton.. so that Facebook Button UI will just fit on its size..  Now its gone.. My fix as of now is just make my own Facebook UIButton and integrate with the Swift SDK.. i'm all running okay now.. I just like the before UI.. Programmatically adding subview produces a mess with my layout.

**Comment by dmdque** [comment]
There's no way to set `readPermissions` or `publishPermissions` once the `LoginButton` has been initialized.

**Comment by yarodevuci** [comment]
I have the same problem. Any fixes so far?

**Comment by dtp5** [comment]
Any update on setting `LoginButton`'s `readPermissions` after initialization, whether done programmatically or via Interface Builder?
