### ISSUE TITLE
Can't update facebook-sdk-swift on Carthage  

### ISSUE THREAD

**Issue by qaysdwekat** [facebook/facebook-sdk-swift#257]
# Facebook Swift SDK Issue

## Environment

Describe your dev environment here, giving as many details as possible. If you have them, make sure to include:

- Xcode Version: `9.4.1`
- Swift Version: `4.1`
- Installation Platform & Verison: `[Carthage]` version `0.30.1`

## Issue Details

I can't install Facebook-SDK-Swift framework 

### Expected Results

install Facebook-SDK-Swift normally 

### Actual Results

```
> carthage update --use-ssh --platform iOS --configuration Release --cache-builds 
*** Fetching Facebook-SDK-Swift
*** Fetching facebook-ios-sdk
*** Fetching Bolts-ObjC
*** Checking out Bolts-ObjC at "1.9.0"
*** Checking out Facebook-SDK-Swift at "0.2.0"
*** Checking out facebook-ios-sdk at "4.35.0"
*** No cache found for Bolts-ObjC, building with all downstream dependencies
*** xcodebuild output can be found in /var/folders/5x/9f7vkcqj5yx33z6ztty3y6mm0000gp/T/carthage-xcodebuild.8l29w2.log
*** Downloading facebook-ios-sdk.framework binary at "4.35.0"
*** Building scheme "Bolts-iOS-Dynamic" in Bolts.xcodeproj
*** Building scheme "Bolts-iOS" in Bolts.xcodeproj
*** Building scheme "FBSDKCoreKit-Dynamic" in FacebookSDK.xcworkspace
*** Building scheme "FBSDKCoreKit-Universal" in FacebookSDK.xcworkspace
*** Building scheme "FBSDKLoginKit-Dynamic" in FacebookSDK.xcworkspace
*** Building scheme "FBSDKIntegrationTests" in FacebookSDK.xcworkspace
Build Failed
	Task failed with exit code 66:
	/usr/bin/xcrun xcodebuild -workspace /Users/user1/Desktop/Release/project-ios/Carthage/Checkouts/facebook-ios-sdk/FacebookSDK.xcworkspace -scheme FBSDKIntegrationTests -configuration Release -derivedDataPath /Users/user1/Library/Caches/org.carthage.CarthageKit/DerivedData/9.4.1_9F2000/facebook-ios-sdk/4.35.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/5x/9f7vkcqj5yx33z6ztty3y6mm0000gp/T/facebook-ios-sdk SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/user1/Desktop/Release/project-ios/Carthage/Checkouts/facebook-ios-sdk)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/5x/9f7vkcqj5yx33z6ztty3y6mm0000gp/T/carthage-xcodebuild.8l29w2.log
```

**Comment by codytwinton** [comment]
Thanks for reporting this issue! This sounds similar to #246. There are some workarounds listed there, which may resolve these issues for you.

For now, I'm going to leave this issue open, since you're dealing with a the current version of Xcode.

**Comment by Nonnus** [comment]
`*** Checking out Facebook-SDK-Swift at "0.2.0"`? 
latest release is 0.3.1 (and there is also a 0.3.2)
maybe you have `0.2.0` version locked in your `cartfile`?

@codytwinton https://github.com/facebook/facebook-sdk-swift/issues/246 is about xcode 10, @qaysdwekat is on 9.4.1, which builds fine on my side (i just tested)

his issue might be related to a bug in carthage described in https://github.com/Carthage/Carthage/pull/2507, i had this issue recently and was not able to build `facebook-ios-sdk` until i manually updated `carthage` using `brew` (`brew install carthage --HEAD`)

**Comment by codytwinton** [comment]
@Nonnus - Thanks for following up on this!

@qaysdwekat - Make sure to use the latest version of the SDK.

**Comment by mark-r2r** [comment]
I'm still getting this and I _am_ using the latest.
