### ISSUE TITLE
Xcode 10 and Swift 4.2

### ISSUE THREAD

**Issue by TofPlay** [facebook/facebook-sdk-swift#262]
## Environment

- Xcode Version: `10.0 Beta 6`
- Swift Version: `4.2.0`
- Installation Platform & Verison: `Cocoapods` version `1.5`

## Issue Details

- **Bugs:** 

![image](https://user-images.githubusercontent.com/1082222/44913875-d9dc6280-ad2e-11e8-94fe-9104a8e8bd80.png)

### Goals

Project compatible with Xcode 10 and Swift 4.2
Suggestion: Create a branch for Swift 4.2

I know that Xcode 10 still in beta but the date of the Keynote is approaching quickly and if we want our application to be ready when iOS 12 will come out the components we use are ready a little before.

### Expected Results

No errors

### Actual Results

Some errors

### Steps to Reproduce

Build a project with your SDK with this setting
![image](https://user-images.githubusercontent.com/1082222/44914187-caa9e480-ad2f-11e8-9256-1bef6a620939.png)

### Code Samples & Details

None

**Comment by codytwinton** [comment]
@TofPlay - Thanks for the heads up! I've created said branch. I'm working on some other pressing tasks currently, but if you have the changes, I'll accept a pull request!

**Comment by txaiwieser** [comment]
iOS 12 is around the corner, please fix this

**Comment by ScribdJobs** [comment]
Bump

**Comment by txaiwieser** [comment]
C'mon Facebook 🙄

**Comment by codytwinton** [comment]
Cheers to @davidrothera for #265 PR. This has been merged into the `swift-4.2` branch.

**Comment by ArunDevOpsiOS** [comment]
Xcode Version: 10.1
Swift Version: 4.2.0

Facebook sent me an  email on Facebook developer account regarding update  the  latest SDK which is used in my app. Despite being changed the latest SDK I am getting the error every time while sign in (login failed: you cant't use facebook to log into this app or website because there's an issue with its implemetation of facebook login .Is there require any extra step along with updation.

**Comment by robtimp** [comment]
@ArunDevOpsiOS I’m sorry to hear that. Please get in touch with Facebook developer support here and they should be able to help figure out what might be going wrong with your specific app: https://developers.facebook.com/support
