### ISSUE TITLE
Carthage with Xcode 10 fails to compile due to Lint issue

### ISSUE THREAD

**Issue by lemonandlime** [facebook/facebook-sdk-swift#283]
Got this error when building the 0.5 version on Carthage.

`*** Building scheme "FacebookCore" in FacebookSwift.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/lemonandlime/Desktop/carthage\ test/Carthage/Checkouts/facebook-sdk-swift/FacebookSwift.xcworkspace -scheme FacebookCore -configuration Release -derivedDataPath /Users/lemonandlime/Library/Caches/org.carthage.CarthageKit/DerivedData/10.0_10A255/facebook-sdk-swift/0.5.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/hk/78hng0957yg6bdhjh1sy2tfh0000gn/T/facebook-sdk-swift SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/lemonandlime/Desktop/carthage test/Carthage/Checkouts/facebook-sdk-swift)`

The last part of the log file generated:
`Linting 'GraphRequestConnectionDelegateBridge.swift' (1/93)
Could not cast value of type 'Swift.Int64' (0x1009c8f90) to 'Swift.String' (0x1009cf4e8).
/Users/lemonandlime/Library/Caches/org.carthage.CarthageKit/DerivedData/10.0_10A255/facebook-sdk-swift/0.5.0/Build/Intermediates.noindex/ArchiveIntermediates/FacebookCore/IntermediateBuildFilesPath/FacebookSwift.build/Release-iphoneos/FacebookCore.build/Script-5257097220F6C9800053B9E3.sh: line 6: 60339 Abort trap: 6           swiftlint
Command PhaseScriptExecution failed with a nonzero exit code`

Im using latest Xcode and carthage 0.31.0

_Originally posted by @lemonandlime in https://github.com/facebook/facebook-sdk-swift/issues/246#issuecomment-431164273_

**Comment by codytwinton** [comment]
@lemonandlime - Thanks for posting this issue. Can you post the version of swiftlint that you're using?

```bash
swiftlint version
```

**Comment by lemonandlime** [comment]
swiftlint version
0.13.0

**Comment by lemonandlime** [comment]
Updating the swiftlint version to the latest 0.27.0 version did the trick. Now it works. Just close this one right? Thanks for the help

**Comment by codytwinton** [comment]
@lemonandlime - Awesome! Glad to hear.
