### ISSUE TITLE
Cannot login with [.PublishActions] permissions

### ISSUE THREAD

**Issue by boomesh** [facebook/facebook-sdk-swift#3]
# Relevant Code
```
if let accessToken = AccessToken.current {
    print(accessToken)
} else {
    let loginManager = LoginManager()
    let completion = {
        (result:LoginResult) in
        switch result {
        case .Success(let grantedPermissions, let declinedPermissions, let accessToken):
            print("YES! \n--- GRANTED PERMISSIONS ---\n\(grantedPermissions) \n--- DECLINED PERMISSIONS ---\n\(declinedPermissions) \n--- ACCESS TOKEN ---\n\(accessToken)")
        case .Failed(let error):
            print("No...\(error)")
        case .Cancelled: 
            print("Fine.")
        }
    }
    loginManager.logIn([.PublishActions], viewController: self, completion: completion)
}
```

I'm not sure if this is intentional, but in `LoginManager.swift`

```
public func logIn(permissions: [PublishPermission] = [.PublishActions],
                  viewController: UIViewController? = nil,
                  completion: ((LoginResult) -> Void)? = nil) {
  let sdkPermissions = permissions.map({ $0.permissionValue.name })
  sdkManager.logInWithReadPermissions(sdkPermissions,
                                      fromViewController: viewController,
                                      handler: LoginManager.sdkCompletionFor(completion))
}
```

When I'm trying to login with publish permissions, it's wrapping around a `logInWithReadPermissions` method.  Is this intentional?  When logging in with that permission, I get the following exception:

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Publish or manage permissions are not permitted to be requested with read permissions.'
```

**Comment by nlutsenko** [comment]
Not intentional, indeed a valid bug.
Thank you for flagging this!
I am on it!

**Comment by nlutsenko** [comment]
@boomesh, thank you for flagging this.
Should be resolved with attached #4.

**Comment by boomesh** [comment]
@nlutsenko nice!  Are there unit/integration tests in this project as well?  Or are we just using travis as a "does this compile" kinda check for now?

**Comment by nlutsenko** [comment]
Frankly, only the latter.
We are in process of adding unit and integration tests to the whole thing, but right now we are the mercy of _we made sure this works manually_.

**Comment by boomesh** [comment]
@nlutsenko fair enough.  Is there a release schedule somewhere?  Or, do you know when `0.1.1` is gonna' be released?

**Comment by nlutsenko** [comment]
Later today, since this is quite an important issue to fix.

**Comment by italoBianchini** [comment]
let permissionsList : [Any] = ["email"]
