### ISSUE TITLE
AccessToken.{current, refreshCurrentToken} failing after relaunch

### ISSUE THREAD

**Issue by SASDOE** [facebook/facebook-sdk-swift#30]
## Process:

1. Login using `LoginButton`
2. Relaunch app
3. Check `AccessToken.current`
  - Returns nil
4. Call `AccessToken.refreshCurrentToken:completion`
  - Returned AccessToken is nil
  - Returned error: `Optional(Error Domain=com.facebook.sdk.core Code=10 "(null)" UserInfo={com.facebook.sdk:FBSDKErrorDeveloperMessageKey=No current access token to refresh})`

## Expected:
Both `AccessToken.current` and `AccessToken.refreshCurrentToken:completion` should return an access token, according to the [docs](https://developers.facebook.com/docs/swift/login)

**Comment by nlutsenko** [comment]
Unfortunately, I can't reproduce the problem using the provided sample app.
After logging in with LoginButton, relaunching the app - `AccessToken.current` returns the `Optional.Some` aka a non-nil value (I just logged it in the AppDelegate).

There might be something weird happening that prevents the token from being saved in the first place to disk.
Unfortunately, without a sample piece of code that cleanly reproduces the problem or better - a test project, there is not much we can do to help diagnose and fix the issue.

**Comment by SASDOE** [comment]
Figured out the issue, I was using the old ApplicationDelegate methods from FBSDK and not `ApplicationDelegate.shared.application` from FacebookCore. Might be something to add to the docs, unless I missed it.

**Comment by woolfel** [comment]
I am having this same problem, what's the fix for it. I'm following the example on the docs page. https://developers.facebook.com/docs/swift/login and AccessToken.current is always nil

thanks

**Comment by woolfel** [comment]
I can login correctly, but the delegate always gets Cancel as the result

extension FacebookViewController: LoginButtonDelegate {
    func loginButtonDidCompleteLogin(loginButton: LoginButton, result: LoginResult) {
        if let accessToken = AccessToken.current {
            print(" the current accesstoken= \(accessToken)")
        }
        
        print("Did complete login via LoginButton with result \(result)")
    }
    
    func loginButtonDidLogOut(loginButton: LoginButton) {
        print("Did logout via LoginButton")
    }
}
Did complete login via LoginButton with result Cancelled

**Comment by djjoyro** [comment]
Hello,

Can you please help me out?

I have this in my AppDelegate.swift
```
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        // Override point for customization after application launch.
        return SDKApplicationDelegate.shared.application(application, didFinishLaunchingWithOptions: launchOptions)
    }
```
And this is in my storyboard:
```
        AccessToken.refreshCurrentToken(AccessTokenRefreshed)

        if AccessToken.current != nil {
            lbl.text="OK"
        }
        else
        {
            let loginButton = LoginButton(readPermissions: [ .publicProfile, .email, .userFriends ])
            loginButton.delegate=self
            //loginButton.loginBehavior = LoginBehavior.systemAccount
            loginButton.center = view.center
            view.addSubview(loginButton)
        }

```

```
func AccessTokenRefreshed(accessToken:AccessToken?, error: Error?)
    {
        if (AccessToken.current != nil)
        {
        lbl.text="OK"
        }
        else
        {
            
            lbl.text="NOK"
        }
    }
```

After killink the application the AccessToken.current is nil.

I'm also getting 'No current access token to refresh' in AccessTokenRefreshed.

What I'm missing ?

Thank you.

**Comment by djjoyro** [comment]
Hello, found the problem, the access token is not stored in the simulator. On the device is working as expected.

**Comment by GuimelGMC** [comment]
I'm working with real device, and I have the same problem...

`FBSDKAccessToken.refreshCurrentAccessToken({ (connection : FBSDKGraphRequestConnection?, result : Any?, error : Error?) in
                if let e = error as NSError? {
                    print(e.localizedDescription)
                } else {
                    self.updateFBCustomerToken()
                }
            })`

in the line `print(e.localizedDescription)` prints `The operation couldn’t be completed. (com.facebook.sdk.core error 10.)` and when I debug the code the `FBSDKAccessToken.current()` is nil... 

I am trying to refresh my accessToken and save to user defaults...

any idea?

Thanks =)

**Comment by srinitude** [comment]
I'm having the same problem as @GuimelGMC! Any solution to this?

**Comment by GuimelGMC** [comment]
i saved the access token info, in userdefault, the tokenstring and experition date, and whe the experition date is >= to today, so i make logout with FBSDKLoginManager

`let loginManager = FBSDKLoginManager()
  loginManager.logOut()`
