### ISSUE TITLE
Facebook login doesn't work in swift 4.2 version of library

### ISSUE THREAD

**Issue by yesnoyes** [facebook/facebook-sdk-swift#301]
Always get this error -

Error Domain=com.facebook.sdk.core Code=3 "(null)" UserInfo={com.facebook.sdk:FBSDKErrorDeveloperMessageKey=Unknown error building URL.}

Cocoapods installation logs -
Installing FBSDKCoreKit 4.39.0 (was 4.38.1)
Installing FBSDKLoginKit 4.39.0 (was 4.38.1)
Installing FBSDKShareKit (4.39.0)
Installing FacebookCore (0.5.0)
Installing FacebookLogin (0.5.0)
Installing FacebookShare (0.5.0)

**Comment by Datastore24Kirill** [comment]
I have a similar error

**Comment by njawahire** [comment]
same issue, any work around?

**Comment by yesnoyes** [comment]
One thread going one here -
https://developers.facebook.com/support/bugs/194351221507588/?disable_redirect=0

Bug is under investigation, hopefully we can get a fix soon.

**Comment by robtimp** [comment]
Temporary work around:

Please add `pod 'FBSDKCoreKit', :git => 'https://github.com/facebook/facebook-objc-sdk.git', :branch => 'master'` to your podfile

**Comment by algera** [comment]
Just clarifying the above (which worked for me) the resultant Podfile will then look like this:

```
    pod 'FBSDKCoreKit', :git => 'https://github.com/facebook/facebook-objc-sdk.git', :branch => 'master'
    pod 'FacebookCore'
    pod 'FacebookLogin'
    pod 'FacebookShare'
```

Or sim.

**Comment by Datastore24Kirill** [comment]
Not work.
My pod file:
pod 'FBSDKCoreKit', :git => 'https://github.com/facebook/facebook-objc-sdk.git', :branch => 'master'
    	pod 'FacebookCore'
    	pod 'FacebookLogin'
    	pod 'FacebookShare'


Error FaceBookCore: Error Domain=com.facebook.sdk.core Code=3 "(null)" UserInfo={com.facebook.sdk:FBSDKErrorDeveloperMessageKey=Unknown error building URL.}

**Comment by monarezio** [comment]
@robtimp method worked, try cleaning the build file or deleting some cache maybe?

@Datastore24Kirill

**Comment by MaximeHouis** [comment]
> @robtimp method worked, try cleaning the build file or deleting some cache maybe?
> 
> @Datastore24Kirill

Method worked for me too.

**Comment by robtimp** [comment]
> Not work.
> My pod file:
> pod 'FBSDKCoreKit', :git => 'https://github.com/facebook/facebook-objc-sdk.git', :branch => 'master'
> pod 'FacebookCore'
> pod 'FacebookLogin'
> pod 'FacebookShare'
> 
> Error FaceBookCore: Error Domain=com.facebook.sdk.core Code=3 "(null)" UserInfo={com.facebook.sdk:FBSDKErrorDeveloperMessageKey=Unknown error building URL.}

Try running `pod deintegrate`, then `pod install` and see if that clears up the issue.

**Comment by JohannesNevels** [comment]
It could be due to return url delegate changes in iOS 12.
I had an issue where I had to change delegate method to get URL delegation working again in a different app.

Old implementation:
func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([Any]?) -> Void) -> Bool {

New implementation:
func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool {

Maybe it's related.. hope this can speed up the progress.

**Comment by yesnoyes** [comment]
Well for now robtimp's solution works -

Temporary work around:

Please add pod 'FBSDKCoreKit', :git => 'https://github.com/facebook/facebook-objc-sdk.git', :branch => 'master' to your podfile

**Comment by superarts** [comment]
Is this workaround still valid? Added

```
    pod 'FBSDKCoreKit', :git => 'https://github.com/facebook/facebook-objc-sdk.git', :branch => 'master'
    pod 'FacebookCore'
    pod 'FacebookLogin'
    pod 'FacebookShare'
```

But still got `Error Domain=com.facebook.sdk.core Code=3 "(null)" UserInfo={com.facebook.sdk:FBSDKErrorDeveloperMessageKey=Unknown error building URL.}`

My `Podfile.lock`:

```
  - FacebookCore (0.5.0):
    - Bolts (~> 1.9)
    - FBSDKCoreKit (~> 4.37)
  - FacebookLogin (0.5.0):
    - Bolts (~> 1.9)
    - FacebookCore (~> 0.5)
    - FBSDKCoreKit (~> 4.37)
    - FBSDKLoginKit (~> 4.37)
  - FacebookShare (0.5.0):
    - Bolts (~> 1.9)
    - FacebookCore (~> 0.5)
    - FBSDKCoreKit (~> 4.37)
    - FBSDKShareKit (~> 4.37)
  - FBSDKCoreKit (4.39.0):
    - Bolts (~> 1.9)
  - FBSDKLoginKit (4.38.1):
    - FBSDKCoreKit
  - FBSDKShareKit (4.38.1):
    - FBSDKCoreKit
```

**Comment by yesnoyes** [comment]
Clean your build folder and try again.

**Comment by r-a-o** [comment]
When can we expect the permanent fix for this? Please keep us posted. Thanks

**Comment by ansonngch** [comment]
anybody facing this issue? com.apple.AuthenticationServices.WebAuthenticationSession error 1

**Comment by NikKovIos** [comment]
What to do if i'm using carthage? I'm getting the `-canOpenURL: failed for URL: “fbauth2:/” (OSStatus error -10814.)"` error.

**Comment by PrakashMaharjan** [comment]
Is this issue not yet fixed by Facebook? Facebook Login with Facebook SDK for iOS v.4.39.0 is not working at all.

I tried all the steps but facebook login is not working for me with latest SDK update.

I am using swift 4.2, with Xcode 10.1, and trying to login in iOS 12.1.2

I tried as one of temporarily workaround method mentioned, this one below in my pod file:

    pod 'FBSDKCoreKit', :git => 'https://github.com/facebook/facebook-objc-sdk.git', :branch => 'master'
    pod 'FacebookCore'
    pod 'FacebookLogin'
    pod 'FacebookShare'

It is not working. I cleaned my project, rebuild but not working.
Tried running pod deintegrate, and then pod install. but this also did not work.

Any help will be appreciated?

Thanks

**Comment by NikKovIos** [comment]
Try. Tell if helped or not. 

pod 'FacebookCore'  #(0.5.0)
pod 'FacebookLogin' #(0.5.0)
pod 'FBSDKCoreKit', '~> 4.38.0'
pod 'FBSDKLoginKit', '~> 4.38.0'

**Comment by yesnoyes** [comment]
If your app is in development state, go to facebook developer console and check if your user has rights to login.
Another thing you should do if you have not done yet, is to delete the app from the device/simulator and also clear the safari cache and try again.

**Comment by PrakashMaharjan** [comment]
Thank you @NikKovIos,

This most people recommended answer did not work for me.

pod 'FBSDKCoreKit', :git => 'https://github.com/facebook/facebook-objc-sdk.git', :branch => 'master'
pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'


Finally your recommendation worked for me.

   pod 'FacebookCore',  '0.5.0'
   pod 'FacebookLogin', '0.5.0'
   pod 'FBSDKCoreKit', '~> 4.38.0'
   pod 'FBSDKLoginKit', '~> 4.38.0'


Thank you so much.

@yesnoyes  no my app was not in development state. It was due to facebook SDK error.
It occurred after I updated my facebook SDK to 4.39.0

Thanks

**Comment by PrakashMaharjan** [comment]
Thank you @NikKovIos,

This most people recommended answer did not work for me.

pod 'FBSDKCoreKit', :git => 'https://github.com/facebook/facebook-objc-sdk.git', :branch => 'master'
pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'

Finally your recommendation worked for me.

pod 'FacebookCore'  #(0.5.0)
pod 'FacebookLogin' #(0.5.0)
pod 'FBSDKCoreKit', '~> 4.38.0'
pod 'FBSDKLoginKit', '~> 4.38.0'

Thank you so much.

@yesnoyes no my app was not in development state. It was due to facebook SDK error.
It occurred after I updated my facebook SDK to 4.39.0

Thanks

**Comment by PrakashMaharjan** [comment]
Thank You @NikKovIos 

Your solution worked for me.

<img width="409" alt="screen shot 2018-12-27 at 6 33 56 pm" src="https://user-images.githubusercontent.com/8100150/50480764-15015080-0a06-11e9-9331-bff47fe1d806.png">


Most people recommended solution as below did not worked for me

<img width="1045" alt="screen shot 2018-12-27 at 6 35 57 pm" src="https://user-images.githubusercontent.com/8100150/50480813-52fe7480-0a06-11e9-84e4-07d4a02b1326.png">

Thanks

@yesnoyes.  No my app was in live mode. The issue started when I updated Facebook SDK to 4.39.0 version.

Thanks @NikKovIos one again.

**Comment by ashishkakkad8** [comment]
Thank You @NikKovIos 

```
pod 'FacebookCore'  #(0.5.0)
pod 'FacebookLogin' #(0.5.0)
pod 'FBSDKCoreKit', '~> 4.38.0'
pod 'FBSDKLoginKit', '~> 4.38.0'
```

Above solution will work like charm!

The solution of @robtimp have an issue because

`pod 'FBSDKCoreKit', :git => 'https://github.com/facebook/facebook-objc-sdk.git', :branch => 'master'`

If you already have 4.39.0 installed by CocoaPods then above line will not work.

**Comment by avsmirnov567** [comment]
@NikKovIos Thanks, worked for me too.

**Comment by Cawfree** [comment]
@robtimp This works just fine, without any need to correct the surrounding project files (`.plist`, `openURL` etc). Thank you. Just curious, what made you think to do this?

**Comment by jonahollman** [comment]
@robtimp's workaround worked for me after cleaning the build folder.

**Comment by jerilyngigigo** [comment]
Our team is currently working with carthage so the proposed workaround is not working for us :((

**Comment by premkumarsepuri** [comment]
> @PrakashMaharjan Try. Tell if helped or not.
> 
> ```
> pod 'FacebookCore'  #(0.5.0)
> pod 'FacebookLogin' #(0.5.0)
> pod 'FBSDKCoreKit', '~> 4.38.0'
> pod 'FBSDKLoginKit', '~> 4.38.0'
> ```

it worked for me thank you

**Comment by mmdock** [comment]
@robtimp 
<img width="568" alt="screen shot 2019-01-10 at 9 44 17 am" src="https://user-images.githubusercontent.com/2423465/50986688-52f97c80-14bc-11e9-99dd-b626d7898fa4.png">

Cannot seem to install 4.39.1?  Can I only do this by running pod 'FBSDKCoreKit', :git => 'https://github.com/facebook/facebook-objc-sdk.git', :branch => 'master' ? seems a little unintuitive

**Comment by robtimp** [comment]
@mmdock No, you probably just need to run `pod repo update` so Cocoapods can find the latest version.

See: https://guides.cocoapods.org/terminal/commands.html#pod_repo_update

**Comment by mmdock** [comment]
@robtimp yeah, i remembered after I posted that message. sorry about that.

**Comment by robtimp** [comment]
@mmdock No problem! It’s easy to forget because `pod install` used to run `pod repo update` every time.

**Comment by antonioreyna** [comment]
hello im getting the same error, any idea how to fix it?

```
Error Domain=com.facebook.sdk.core Code=3 "(null)" UserInfo={com.facebook.sdk:FBSDKErrorDeveloperMessageKey=Unknown error building URL.}
```

my pod is like:

```
pod 'FBSDKCoreKit'
	pod 'FBSDKLoginKit'
	pod 'FacebookCore'
	pod 'FacebookLogin'
	pod 'FacebookShare'
```

**Comment by premkumarsepuri** [comment]
try with this names 
 pod 'FacebookCore'  #(0.5.0)
pod 'FacebookLogin' #(0.5.0)
pod 'FBSDKCoreKit', '~> 4.38.0'
pod 'FBSDKLoginKit', '~> 4.38.0'

**Comment by premkumarsepuri** [comment]
pod 'FacebookCore'  #(0.5.0)
pod 'FacebookLogin' #(0.5.0)
pod 'FBSDKCoreKit', '~> 4.38.0'
pod 'FBSDKLoginKit', '~> 4.38.0'

**Comment by antonioreyna** [comment]
Hello, now it is working but when i hit continue on the web view i get this error

`Login Error: There is an error in logging you into this application. Please try again later.`

Any idea guys?

**Comment by mmdock** [comment]
@antonioreyna I believe Facebook was having an outage 4 days ago when you posted that.

**Comment by kaya96** [comment]
Hi!! i tried pod 'FBSDKCoreKit', :git => 'https://github.com/facebook/facebook-objc-sdk.git', :branch => 'master' but when i build i get this error

No known class method for selector 'extractPermissionsFromResponse:grantedPermissions:declinedPermissions:'

Any help will be appreciated

**Comment by Mikkelet** [comment]
any update to this? We are having this problem, using Flutter's facebook package 2.0
