### ISSUE TITLE
Unable to find a specification for `FacebookCore`

### ISSUE THREAD

**Issue by frozenL** [facebook/facebook-sdk-swift#40]
Hi, I tried to use Facebook API following steps in the file. But when I got to 'pod install', it showed

Analyzing dependencies
[!] Unable to find a specification for `FacebookCore`

Could anyone tell me how to solve it?

**Comment by nlutsenko** [comment]
This means that your local CocoaPods repo is out of date.
I would suggest running `pod repo update`, then `pod install` or `pod update` might also trigger repo update.

Let me know where this helps.

**Comment by frozenL** [comment]
Hi, thanks for the prompt reply :) I tried `pod repo update` and then `pod install`, but it failed again. Is there any other way to solve it?
![screen shot 2016-08-15 at 23 11 29](https://cloud.githubusercontent.com/assets/12996936/17681466/ce86590a-633d-11e6-8724-d3de0d2d6336.png)

**Comment by frozenL** [comment]
I checked the pod repo, and the URL is https://github.com/CocoaPods/Specs.git.

**Comment by nlutsenko** [comment]
Her his the pod spec on CocoaPods - https://cocoapods.org/pods/FacebookCore
Meaning that it's installable and visible.

Probably something is broken about your local pod spec repo.
Try removing `~/.cocoapods` from your Mac and/or re-running `pod setup`.

**Comment by nlutsenko** [comment]
Feel free to reopen the issue if you are still running into problems, or open a new one if there is anything we can help you with.

**Comment by frozenL** [comment]
Sorry for the late reply. I did it as you said just now and it worked. Thanks!
