### ISSUE TITLE
When is swift 3 support planned?

### ISSUE THREAD

**Issue by gsabran** [facebook/facebook-sdk-swift#41]
I can't use the pod with xcode 8 (beta 6) I guess it's because the code hasn't been ported to swift3. Do you have an idea of when we can expect an update on that front?

**Comment by nlutsenko** [comment]
This is a really good question! Thank you for asking!

Our plan is to add Swift 3 support the moment it goes GM, meaning sometime late in August/September (depends on Apple, not us). In the meantime - you are very welcome to use the Swift 3 migration tool on the current set of source code to update it to Swift 3. 

There shouldn't be a lot of violations that need to be fixed, but if you find ones that need manual intervention or something isn't obvious - please open an issue and we'll take a closer look and would love to work with you to resolve it!
