### ISSUE TITLE
swift3 xcode 8

### ISSUE THREAD

**Issue by edwardvalentini** [facebook/facebook-sdk-swift#45]
is there an ETA on a swift3 / xcode8 release?  thank you.

**Comment by nlutsenko** [comment]
Our plan is to add Swift 3 support the moment it goes GM, meaning sometime late in August/September (depends on Apple, not us). In the meantime - you are very welcome to use the Swift 3 migration tool on the current set of source code to update it to Swift 3.

There shouldn't be a lot of violations that need to be fixed, but if you find ones that need manual intervention or something isn't obvious - please open an issue and we'll take a closer look and would love to work with you to resolve it!

Most likely, the `0.3` release is the one that is going to support Swift 3, meaning that 0.2 is going to be the last one to support Swift 2.3.

**Comment by rromanchuk** [comment]
reopen please

**Comment by i-am-chris** [comment]
same question
