### ISSUE TITLE
'FBSDKCoreKit.framework' does not get built by 'Carthage update'

### ISSUE THREAD

**Issue by lindanordstrom** [facebook/facebook-sdk-swift#49]
Hi, I am trying to use `Carthage update` to get all the Facebook frameworks. 
When carthage is done I can see the following framworks in Carthage/Build/iOS
`Bolts.framework`
`FacebookCore.framework`
`FacebookLogin.framework`
`FacebookShare.framework`

But not the 
`FBSDKCoreKit.framework`

Carthage version 0.17.2
Logs:

```
Lindas-MacBook-Pro:External linda$ brew upgrade carthage
Error: carthage 0.17.2 already installed
Lindas-MacBook-Pro:External linda$ Carthage update
*** Fetching facebook-sdk-swift
*** Fetching facebook-ios-sdk
*** Fetching Bolts-ObjC
*** Checking out Bolts-ObjC at "1.8.4"
*** Checking out facebook-sdk-swift at "0.1.1"
*** Downloading facebook-ios-sdk.framework binary at "4.15.0"
*** Checking out facebook-ios-sdk at "sdk-version-4.15.0"
*** xcodebuild output can be found in /var/folders/px/6h8vf5gd2vbgfz716vll12h80000gp/T/carthage-xcodebuild.xeASTg.log
*** Building scheme "Bolts-macOS" in Bolts.xcodeproj
*** Building scheme "Bolts-tvOS-Dynamic" in Bolts.xcodeproj
*** Building scheme "Bolts-watchOS-Dynamic" in Bolts.xcodeproj
*** Building scheme "Bolts-iOS-Dynamic" in Bolts.xcodeproj
*** Building scheme "Bolts-tvOS-Dynamic" in FacebookSDK.xcworkspace
*** Building scheme "Bolts-watchOS-Dynamic" in FacebookSDK.xcworkspace
*** Building scheme "Bolts-macOS" in FacebookSDK.xcworkspace
*** Building scheme "Bolts-iOS-Dynamic" in FacebookSDK.xcworkspace
*** Building scheme "FacebookLogin" in FacebookSwift.xcworkspace
*** Building scheme "FacebookCore" in FacebookSwift.xcworkspace
*** Building scheme "FacebookShare" in FacebookSwift.xcworkspace
```

**Comment by pivotalstitch** [comment]
Any updates on this? Having the same issues.

**Comment by erikbeerepoot** [comment]
Make sure that your carthage is the latest version (the version in this post is out of date). Earlier versions of carthage have different behavior with respect to selecting the schemes that it will build, resulting in Bolts being built only. `0.18.1` worked for me.

If you're still having trouble, you can work around this issue by going to `carthage/checkouts/facebook-ios-sdk` and running `carthage build --no-skip-current --platform ios` (or whatever your particular build command is). This should put the resulting frameworks in `carthage/build`. Then use as normal.

**Comment by lindanordstrom** [comment]
@erikbeerepoot the second solution did the trick for me (using xcode 8.1)
thanks!
