### ISSUE TITLE
No such module UIKit ?

### ISSUE THREAD

**Issue by misbell** [facebook/facebook-sdk-swift#50]
![2016-09-01 at 5 25 pm](https://cloud.githubusercontent.com/assets/356572/18185055/b10de166-7069-11e6-9e31-ab2bc0336751.png)

No such module UIKit ?

**Comment by nlutsenko** [comment]
Looks like you cloned the project without submodules.
Please run `git submodule update --init --recursive` after you cloned the repository.

**Comment by nlutsenko** [comment]
One more note - you would also need to close and re-open the project after you fetched all the submodules to make sure that Xcode picks up the configurations.
