### ISSUE TITLE
Framework not found FBSDKShareKit

### ISSUE THREAD

**Issue by ronzohan** [facebook/facebook-sdk-swift#54]
Hi,

I have successfully installed facebook sdk using carthage. I then linked facebook sdk to my created framework. When I try to build my project, it works fine but when I try to build my project with a module on my framework that imports FacebookShare it will show this compile-time error. 

`ld: framework not found FBSDKShareKit for architecture x86_64` 
`clang: error: linker command failed with exit code 1 (use -v to see invocation)`

Below is my current project where the fbservice.xcodeproj is my framework
<img width="255" alt="screen shot 2016-09-12 at 8 40 14 pm" src="https://cloud.githubusercontent.com/assets/5672125/18436115/2ba1b110-7929-11e6-8f29-9da1d4feb9a6.png">

Any help?

**Comment by EvsenevDev** [comment]
Hi, maybe it`s help you. This works for me.

<img width="210" alt="2016-09-15 9 55 56" src="https://cloud.githubusercontent.com/assets/20614330/18540933/ad7c4422-7b2a-11e6-90c2-8b7135457f0d.png">


<img width="738" alt="2016-09-15 9 56 13" src="https://cloud.githubusercontent.com/assets/20614330/18540934/ad80c768-7b2a-11e6-8dd1-399484a2626f.png">

**Comment by nlutsenko** [comment]
@EvsenevDev, yup, that's the preferred way of installing the SDK into your app.
@ronzohan, I would recommend taking a detailed look at the repo's README, it has outlined instructions for Carthage/CocoaPods as well as for compiling manually.
If you run into any issues further - please open a new issue.
