### ISSUE TITLE
Module compiled with Swift 2.3 cannot be imported in Swift 3.0

### ISSUE THREAD

**Issue by EvsenevDev** [facebook/facebook-sdk-swift#56]
Hi, I have error:
`Module compiled with Swift 2.3 cannot be imported in Swift 3.0 `

I tried to do `carthage update`, but it did not help me.
And set `Use Legacy Swift Language Version` to `YES`, did not help me too.

Use:
Xcode 8, Swift 3

**Comment by GioValentin** [comment]
When will there be a swift 3.0 release? Because I am running into the same problem. I tried to downgrade from 3.0 to 2.3 but now my other cocoapods wont work.

**Comment by Nishadarora** [comment]
Same problem

**Comment by mauropiccini** [comment]
+1

**Comment by cdtadmin** [comment]
+1 more

**Comment by AlexanderBaranovski** [comment]
+1

**Comment by Alex293** [comment]
+1

**Comment by Mikkelu** [comment]
+1

**Comment by Drag11** [comment]
yep, Nikita, please assist

**Comment by nlutsenko** [comment]
This is ultimately is going to get resolved when we have #53 aka Swift 3 support.
Let's continue our discussion there.
