### ISSUE TITLE
Unclear Carthage installation instructions

### ISSUE THREAD

**Issue by AndrewBarba** [facebook/facebook-sdk-swift#6]
In order to build with Carthage you need to at a minimum drag in:

`FacebookCore.framework`
`FBSDKCoreKit.framework`
`Bolts.framework` 

as well as update the build phase script to include the files:

`$(SRCROOT)/Carthage/Build/iOS/Bolts.framework`
`$(SRCROOT)/Carthage/Build/iOS/FBSDKCoreKit.framework`
`$(SRCROOT)/Carthage/Build/iOS/FacebookLogin.framework`

If you want to include login and/or share, then you need to include those frameworks and add them to the build phase.

Without doing these steps, the project will actually build correctly but you get a nasty "Image not found" crash when the device launches the app

**Comment by nlutsenko** [comment]
Noted, though the last paragraph there actually mentions the nested dependencies.
