### ISSUE TITLE
Compiler error with Xcode 8 & Swift 3

### ISSUE THREAD

**Issue by balboah** [facebook/facebook-sdk-swift#62]
I apologise in advance if this is a newbie error but while trying to follow the install instructions with Cocoapods 1.0.1:

Podfile:
```
platform :ios, '10.0'

target 'App' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'

  target 'AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

I'm running
`pod install`

```
Installing Bolts (1.8.4)
Installing FBSDKCoreKit (4.15.1)
Installing FBSDKLoginKit (4.15.1)
Installing FBSDKShareKit (4.15.1)
Installing FacebookCore (0.2.0)
Installing FacebookLogin (0.2.0)
Installing FacebookShare (0.2.0)
```

It then tells me to open MeetApp.xcworkspace from now on, which I do.
But then Xcode asks if I want to covert Pods to Swift 3 or 2.3 as it can't compile FacebookCore. Some example errors (out of 84 of them):
`AppEventName.swift: Use of undeclared type 'ExpressibleByStringLiteral'`
`UserProfile.swift: Unknown attribute 'escaping'`

All the .framework file becomes red and I'm failing to import them into my project.

**Comment by kavehmb** [comment]
I let the xcode convert the code to swift 3 and it compiles well.

**Comment by HasanSa** [comment]
preferred to change your PodFile to:

pod 'FacebookCore', :git => "https://github.com/facebook/facebook-sdk-swift"
pod 'FacebookLogin', :git => "https://github.com/facebook/facebook-sdk-swift"
pod 'FacebookShare', :git => "https://github.com/facebook/facebook-sdk-swift"

rather than to let the Xcode convert.

**Comment by hematit** [comment]
I have totally the same problem like @balboah 
Using git in PodFile didn't solve the problem for me.

```
Installing Bolts (1.8.4)
Installing FBSDKCoreKit (4.16.0)
Installing FBSDKLoginKit (4.16.0)
Installing FBSDKShareKit (4.16.0)
Installing FacebookCore (0.2.0)
Installing FacebookLogin (0.2.0)
Installing FacebookShare (0.2.0)
```

```
pod --version 1.0.1
Xcode Version 8.0
```

**Comment by quicken** [comment]
I got it working with hasanSa instructions, but only after wiping my project and starting fresh. Lucky for me i am on a brand new project. 

I setup a simple single view container swift project.
configured Podfile with the git repo, installed the pods, when prompted converted all targets to swift 3. The final piece of the puzzle for me was resolving the update xcode projects warning which i had to do 3 times (each time it would fix one more warning) now it works with swift 3. Nothing is easy with swift its still a moving target. good luck!

**Comment by smahajan28** [comment]
Same problem occurred. Just updated my cocoapods and xcode, now Facebook SDK has lot of errors. Adding git url in podfile not working for me too. Any help is appreciated.

**Comment by cristiangoncas** [comment]
I'm experiencing the same error.
Xcode 8.0
Pod 1.1.0.rc.3

Adding git urls not working for me either.
Some other solution?

**Comment by balboah** [comment]
Adding git urls doesn't seem to help. Even after clearing CocoaPods cache and removing Pods dir as well as wcworkspace.

```
Analyzing dependencies
Pre-downloading: `FacebookCore` from `https://github.com/facebook/facebook-sdk-swift`, commit `bb58af1e1bbb72388f315c51d60839b1c0c901fe`
Pre-downloading: `FacebookLogin` from `https://github.com/facebook/facebook-sdk-swift`, commit `bb58af1e1bbb72388f315c51d60839b1c0c901fe`
Pre-downloading: `FacebookShare` from `https://github.com/facebook/facebook-sdk-swift`, commit `bb58af1e1bbb72388f315c51d60839b1c0c901fe`
Downloading dependencies
Installing Bolts (1.8.4)
Installing FBSDKCoreKit (4.15.1)
Installing FBSDKLoginKit (4.15.1)
Installing FBSDKShareKit (4.15.1)
Installing FacebookCore (0.2.0)
Installing FacebookLogin (0.2.0)
Installing FacebookShare (0.2.0)
Generating Pods project
Integrating client project
```

I get the same versions as listed before and many issues after converting to Swift 3 (funny it's now 93 issues instead of 84).
I guess I'll just mock the login part until I know more about Swift and Xcode :)

**Comment by balboah** [comment]
Somehow it magically worked now after I re-created a new project, after I've already added a different pod (Alamofire).
There weren't even any compile errors or warnings, while the listed versions are still the same. Super strange.

**Comment by aerciyas** [comment]
When I followed HasanSa's instruction it didn't work at first(got errors while running pod install), but then I ran "pod repo update" in the terminal first then followed HasanSa's suggestion again and everything worked.
