### ISSUE TITLE
how to access the value of "email" from success response. 

### ISSUE THREAD

**Issue by SebastainMisas** [facebook/facebook-sdk-swift#63]
I have an issue where the success response does not give me back the JSON format i was expecting.. 

class FacebookLoginHelper {

```
class func login(controller:UIViewController, successBlock: @escaping ( _ status:Bool, _ response:JSON?, _ token:String?, _ id:String?) -> Void) {

    let loginManager = LoginManager()
    let readPermissions: [ReadPermission] = [.publicProfile, .email, .userFriends]

    loginManager.logIn(readPermissions, viewController: controller) { loginResult in
        switch loginResult {
        case .failed(let error):
            print("failed", error)
            successBlock(false, nil, nil,nil)
            return

        case .cancelled:
            successBlock(false, nil , nil,nil)

        case .success(let grantedPermissions, let declinedPermissions, let accessToken):

            let connection = GraphRequestConnection()
            var request = GraphRequest.init(graphPath: "me")
            request.parameters = ["fields":"email,first_name,last_name,picture.width(1000).height(1000),birthday,gender"]

            connection.add(request, completion: {
                (response, result) in
                print("Facebook graph Result:", result)
                    let json = JSON(result)
                    print("Facebook graph Result:", json)
                    let id = json["id"].string
                    successBlock(true, json, accessToken.authenticationToken ,id)


            })
            connection.start()

        }
    }

}
```

}

THE OUTPUT: 
success(FacebookCore.GraphResponse(rawResponse: Optional({
    email = "abc@gmail.com";
    "first_name" = test;
    gender = male;
    id = 1234556788900;
    "last_name" = test;
    picture =     {
        data =         {
            height = 1224;
            "is_silhouette" = 0;
            url = "test.jpg";
            width = 1224;
        };
    };
})))

**Comment by jgreen84** [comment]
I'm having a similar experience. I'm stuck now at how to parse this output into a useful format. The Facebook Docs aren't up to date with the Swift 3 syntax. Any help?

**Comment by rslim087g** [comment]
how do you parse that

**Comment by SebastainMisas** [comment]
I found the issue. Looks like Facebook needs to update their documentation here:
https://developers.facebook.com/docs/swift/graph

Here is the solution(use this instead): 
let params = ["fields":"email,first_name,last_name,picture.width(1000).height(1000),birthday,gender"]
                let graphRequest = GraphRequest(graphPath: "me", parameters: params)
                    graphRequest.start {
                        (urlResponse, requestResult) in
                        switch requestResult {
                        case .failed(let error):
                            print("error in graph request:", error)
                            break
                            // Handle the result's error
                            
                        case .success(let graphResponse):
                            if let responseDictionary = graphResponse.dictionaryValue {
                                let json = JSON(responseDictionary)
                                let id = json["id"].string!
                               successBlock(true, json, accessToken.authenticationToken ,id)
                            }
                        }  
                    
                }

**Comment by nlutsenko** [comment]
@SebastainMisas, thanks for writing this documentation! That was super helpful!
I am going to update the page you linked above in a few moments.

**Comment by nlutsenko** [comment]
Small and quick update on this. You don't have to re-parse JSON form the `dictionaryValue`, since it's already parsed for you. The response are usually in a JSON Object aka `Dictionary`, meaning that just after using `graphResponse.dictionaryValue?["id"]` you are good to go.

**Comment by nlutsenko** [comment]
Just updated documentation on https://developers.facebook.com/docs/swift/graph
It uses both Swift 3 syntax, as well as has an example of how to extract values from the fetched response.
