### ISSUE TITLE
 Facebook Login issue in swift 3, iOS 10, xcode 8, systemAccount not logged in

### ISSUE THREAD

**Issue by sudheer-suriefy** [facebook/facebook-sdk-swift#67]
I have added Facebook sdk from cocoapods. Below are the line in my pod file.
My environment : Xcode 8, iOS 10, Swift 3.

pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'

I implemented following delegate methods.

public func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any] = [:]) -> Bool 
public func application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any) -> Bool

I called login with .systemAccount behaviour. Below is the code snippet

let loginManager = LoginManager()
loginManager.loginBehavior = LoginBehavior.systemAccount//FBSDKLoginBehavior.systemAccount
loginManager.logIn([.publicProfile], viewController: self) { 

If System account in iPhone is logged in, its working fine. But when it is not logged In, blank screen appears and it goes no where. I uploaded the image of blank screen.

Regards,
Sudheer Myneni
![1729yl](https://cloud.githubusercontent.com/assets/20552121/19031931/a3c2bee0-8974-11e6-97b3-6f6143f06550.jpg)

**Comment by AndrewBarba** [comment]
Not sure if this is related, but with version `0.2.0` make sure you pass in the appropriate options to `application(open:url:options)`:

```
if SDKApplicationDelegate.shared.application(application, open: url, options: [
    .sourceApplication: sourceApplication,
    .annotation: annotation
]) {
    return true
}
```

After passing in the options things started working as expected

**Comment by Dane456** [comment]
Just as backup to @AndrewBarba's post, the `application(open:url:options)` is in reference to the AppDelegate method, which by default in apps (at least mine) is not included.
