### ISSUE TITLE
What about setUserID and userProperties?

### ISSUE THREAD

**Issue by eikebartels** [facebook/facebook-sdk-swift#70]
I would like to set some user properties. 

I have seen it in https://developers.facebook.com/docs/analytics/properties How can I use it?

**Comment by mbalex99** [comment]
Yeah this looks completely missing from the Swift SDK

**Comment by nlutsenko** [comment]
Hey guys, this is indeed missing from the Swift SDK, as it's a new addition.
Looking forward to adding these, as it's an incredibly nice feature!

**Comment by eikebartels** [comment]
@nlutsenko thanks for confirmation. That means we have to ship back to the Objective C SDK for now? Or is it possible to use both?

**Comment by nlutsenko** [comment]
Technically, it's possible to use both at the same time.
And you are implicitly using the ObjC one, since the Swift SDK depends on it. 😁

**Comment by nlutsenko** [comment]
#147 merged which includes Swift support for it.
Going to be released soon with version 0.3.0 of the Swift SDK.
