### ISSUE TITLE
Blank Safari screen after confirming permissions when using browser/native LoginBehavior

### ISSUE THREAD

**Issue by MoridinBG** [facebook/facebook-sdk-swift#72]
I recently migrated my app from Swift 2.3 to 3.0

After that, trying to login to facebook results in blank Safari screen after confirming the app permissions. There are no errors in the console and the logIn completion handler does not fire.
If I tap Done  the completion handler fires with cancelled.
This happens both on device (10.0.1) & simulator (9.3, 10.0.1)

If I use web LoginBehavior, it works fine - after confirming permissions the completion handler fires.
This also happens with the older Obj-C SDK. Actually, I finally migrated to the Swift sdk, hoping that it will fix it.

This seems similar to #66 and #67
I tried adjusting transport security, but that didn't work and I am not using the AppDelegate url method.

**Comment by carloscorreia94** [comment]
It's not working with me either. Xcode 8 and Swift 3. Running on iOS 10

**Comment by carloscorreia94** [comment]
I've posted an Issue here describing my situation https://github.com/facebook/facebook-sdk-swift/issues/74

**Comment by dasoga** [comment]
+1

**Comment by MoridinBG** [comment]
The issue is really simple. You have to implement the following method in your App Delegate:

    func application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any) -> Bool

And **pass the URL to FBSDKApplicationDelegate. That's it.** Login works as expected now

What broke for some people that already implement this is that it is fairly common to only pass the fb authorize URL to the sdk delegate  (as you should!) and it is common to do

    if url.scheme!.hasPrefix("fb\(FBSDKSettings.appID())")


but FBSDKSettings.appID() is an implicitly unwrapped optional (String!) and Swift 3 changed how they work (https://github.com/apple/swift-evolution/blob/master/proposals/0054-abolish-iuo.md)  and the string interpolation expands it to "fbOptional(...". If this is the case, you should change it to

    if let fbSDKAppId = FBSDKSettings.appID(), url.scheme!.hasPrefix("fb\(fbSDKAppId)"), url.host == "authorize"

(you could just append another ! to FBSDKSettings.appID() but I hate this)

It's not really Facebook's job what URLs is your app opening, so you should only pass it the authentication URL.
