### ISSUE TITLE
Safari Blank Page After Login 

### ISSUE THREAD

**Issue by carloscorreia94** [facebook/facebook-sdk-swift#74]
I am having trouble to get the Facebook Login component to resolve while using the following environment:

Swift 3.0 in Xcode 8 Facebook SDK for Swift (0.2.0) Running on iOS 10

I've followed all the required steps to get it going ([iOS Getting Started ](https://developers.facebook.com/quickstarts/1619016601757957/?platform=ios)and [Swift Getting Started](https://developers.facebook.com/docs/swift/login)), even the steps not mentioned in here such as adding the default AppDelegate methods as follow:

```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {

        FacebookCore.SDKApplicationDelegate.shared.application(application, didFinishLaunchingWithOptions: [
            .sourceApplication: application,
            ])
        return true

    }

private func application(app: UIApplication, openURL url: URL, options: [UIApplicationOpenURLOptionsKey : Any]) -> Bool {
        return FacebookCore.SDKApplicationDelegate.shared.application(app, open: url, options: [
            .sourceApplication: app,
            ])
    }

@available(iOS 9.0, *)
private func application(application: UIApplication, openURL url: URL, sourceApplication: String?, annotation: AnyObject) -> Bool {
    return FacebookCore.SDKApplicationDelegate.shared.application(application, open: url, sourceApplication: sourceApplication, annotation: annotation)
}
```

As for the Info.plist contents, concerning the Facebook part, I assume I have all the required tags and even some others that seemed helpful to resolve the situation, found in some questions on SO and issues on Github:

```
<key>CFBundleURLTypes</key>
    <array>
        <dict>
            <key>CFBundleURLSchemes</key>
            <array>
                <string>fb1619016601757957</string>
            </array>
        </dict>
    </array>
<key>FacebookAppID</key>
    <string>1619016601757957</string>
    <key>FacebookDisplayName</key>
    <string>Nossa Cidade</string>
    <key>LSApplicationQueriesSchemes</key>
    <array>
        <string>fbapi</string>
        <string>fb-messenger-api</string>
        <string>fbauth2</string>
        <string>fbshareextension</string>
    </array>
<key>NSAppTransportSecurity</key>
    <dict>
        <key>NSExceptionDomains</key>
        <dict>
            <key>facebook.com</key>
            <dict>
                <key>NSIncludesSubdomains</key>
                <true/>
                <key>NSExceptionRequiresForwardSecrecy</key>
                <true/>
            </dict>
            <key>fbcdn.net</key>
            <dict>
                <key>NSIncludesSubdomains</key>
                <true/>
                <key>NSExceptionRequiresForwardSecrecy</key>
                <true/>
            </dict>
            <key>akamaihd.net</key>
            <dict>
                <key>NSIncludesSubdomains</key>
                <true/>
                <key>NSExceptionRequiresForwardSecrecy</key>
                <true/>
            </dict>
        </dict>
    </dict>
```

For the last and core part, super simplified, I attach the login button logic in my login controller.

```
override func viewDidLoad() {
        super.viewDidLoad()

 loginButton = LoginButton(readPermissions: [.publicProfile, .userFriends, .email])
        loginButton.center =  view.center
        loginButton.frame.origin = CGPoint(x: loginButton.frame.origin.x,y: loginBtn.frame.origin.y + 80)
        self.view.addSubview(loginButton)
       loginButton.delegate = self

}

 func loginButtonDidCompleteLogin(_ loginButton: LoginButton, result: LoginResult) {

        switch result {
        case .success(let grantedPermissions, _, let accessToken):
            print("facebook success")
            print(accessToken.authenticationToken)
            break
        case .cancelled:
            print("facebook cancelled")
            break

        case .failed(let error):
            print("facebook error")
            break
        }
}

 func loginButtonDidLogOut(_ loginButton: LoginButton) {
        print("User has logged out")
 }
```

I've gone through a lot of SO questions, Github issues, and there are some developers running into the same situation as me, without any concrete response about the possible outcome of this error. What happens in the end, is that I get a big fat LoginResult.cancelled callback, not what I intend.

The output from the console, related to this is:
`-canOpenURL: failed for URL: "fbauth2:/" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"`

Any help would be appreciated. Thank you!

**Comment by Patrez** [comment]
I had the same issue, fixed it by implementing this method in AppDelegate.swif. I am also using cocoapods to import FacebookSDK.

func application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any) -> Bool {
        let handled = FBSDKApplicationDelegate.sharedInstance().application(application, open: url, sourceApplication: sourceApplication, annotation: annotation)
        return handled
    }

**Comment by carloscorreia94** [comment]
Didn't work for me @Patrez . And I find it strange to use components from the Objective C library, FBSDK.

**Comment by kiswara** [comment]
I had the same issue (with none of the above solutions helping to solve the problem), and this is what did the trick for me after searching for a couple of days:

http://stackoverflow.com/questions/38689631/how-to-use-facebook-ios-sdk-on-ios-10

**Comment by jgreen84** [comment]
I've written an article here explaining everything I had to do to get this all working, most of which I had to figure out as the Facebook Docs weren't up to date at time of writing. This includes the problem you've had with not returning to the application after login. Hope it's helpful to some. let me know if you think there's any improvements I could make.
http://jgreen3d.com/facebook-sdk-swift-3/

**Comment by onurbilic** [comment]
+1  I had same issue. I tried all written solutions above but it didn't worked for me.  Still white, blank page opening in safari when I touched login with Facebook. 

I am using Swift 3.0 in Xcode 8 and Facebook latest cocoapods SDK  for Swift  Running on iOS 10

Can anyone help about this issue. Thank you.

**Comment by MoridinBG** [comment]
The issue is really simple. You have to implement the following method in your App Delegate:
    func application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any) -> Bool
And **pass the URL to FBSDKApplicationDelegate. That's it.** Login works as expected now

What broke for some people that already implement this is that it is fairly common to only pass the fb authorize URL to the sdk delegate  (as you should!) and it is common to do
    if url.scheme!.hasPrefix("fb\(FBSDKSettings.appID())")

but FBSDKSettings.appID() is an implicitly unwrapped optional (String!) and Swift 3 changed how they work (https://github.com/apple/swift-evolution/blob/master/proposals/0054-abolish-iuo.md)  and the string interpolation expands it to "fbOptional(...". If this is the case, you should change it to
    if let fbSDKAppId = FBSDKSettings.appID(), url.scheme!.hasPrefix("fb\(fbSDKAppId)"), url.host == "authorize"
(you could just append another ! to FBSDKSettings.appID() but I hate this)

It's not really Facebook's job what URLs is your app opening, so you should only pass it the authentication URL.

**Comment by r-a-o** [comment]
Still doesn't work. Can somebody please release a fix for this?!

**Comment by MoridinBG** [comment]
It works fine. See above.

**Comment by r-a-o** [comment]
@MoridinBG Already tried everything listed above, it only works with the ObjC lib by Bridging Header but doesn't work for Swift lib. 

Throws the following error upon tap of Facebook login button,

> -canOpenURL: failed for URL: "fbauth2:/" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"

Then opens Safari, collects permission, then fails to return to app. (Blank screen)

I am on Xcode 8.0 running Swift 2.3 app.

**Comment by gauravcanon** [comment]
I have also faced this problem from past 1 month.Followed all the steps and tutorials but nothing worked. I was integrating facebook login with firebase in ios 10 swift 3. Finally, I m able to successfully implement it. I corrected it by making following changed in AppDelegate file.

`    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        
        FIRApp.configure()
        FBSDKApplicationDelegate.sharedInstance().application(application, didFinishLaunchingWithOptions: launchOptions)
          return true
    }
    

    @available(iOS 9.0, *)
    func application(_ application: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any])
        -> Bool {
            var shouldOpen :Bool = FBSDKApplicationDelegate.sharedInstance().application(application,  open: url, sourceApplication:options[UIApplicationOpenURLOptionsKey.sourceApplication] as! String!,annotation: options[UIApplicationOpenURLOptionsKey.annotation])
            return shouldOpen
    }
    
    // for iOS below 9.0
    func application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any) -> Bool {
        var shouldOpen :Bool = FBSDKApplicationDelegate.sharedInstance().application(application,open: url as URL!,sourceApplication: sourceApplication,annotation: annotation)
        return shouldOpen
    }
`


I Hope it might help others 

tested on ios 10.2 Emulator, iPhone 6 Plus running with 10.2

**Comment by yoman07** [comment]
I tried everything above and it doesn't work. Do you have any solution for this problem?

**Comment by Cruzv35** [comment]
gauravcanon Thanks man!

**Comment by rocketedaway** [comment]
I a having the same issue. @carloscorreia94 did you end up resolving this issue with Facebook Login?

**Comment by calvinsug** [comment]
I use FBSDKLoginKit 4.22 and i had the same issues, i had enable my keychain sharing, add my info.plist, and configure it in appdelegate.swift, but still when i click confirm login after facebook web appear, the blank page appear

**Comment by emadd** [comment]
I tried absolutely everything documented and mentioned until I discovered this...

https://stackoverflow.com/a/39544399/182544

And it WORKS

**Comment by carloscorreia94** [comment]
Yes, I did. Turned out the function signature in appDelegate was mismatching. Take care when copying, I guess the argument name was omited , i.e (_ something) and was not being called. I know its generic, but was long time ago. This was really not a bug, so I'm gonna close the issue. Sorry for the late reply anyway.
