### ISSUE TITLE
Compiling problems

### ISSUE THREAD

**Issue by sargeras55** [facebook/facebook-sdk-swift#75]
My project not compiling CocoaPod FacebookCore. And when cloning project, break and other libraries. My project on Swift 3 and this lib on 2.3, swift legacy is true.

`http://i.stack.imgur.com/px2Zz.jpg`

**Comment by nlutsenko** [comment]
Hey @sargeras55,

We are officially Swift 3.0 starting from [version 0.2.0](https://github.com/facebook/facebook-sdk-swift/releases/tag/0.2.0).
Please update to the latest version of the SDK and let us know if you are running into any issues.

**Comment by sargeras55** [comment]
Thanks.
