### ISSUE TITLE
can't able to retrieve facebook friend's birthday using facebook sdk.

### ISSUE THREAD

**Issue by NiteshKhandal** [facebook/facebook-sdk-swift#77]
i just want to retrieve all the friend's birthday date and email using facebook sdk in ios but i can only retrieve friends : id , frist_name , last_name, name , picture but birthday can not.

please help me , it's so urgent as soon as possible.

**Comment by nlutsenko** [comment]
Hi @NiteshKhandal,

There are a few gotchas to retrieving friend's birthdays:
- You need to request `user_friends` permission when logging into the app
- Starting from Graph API 2.0 (which was introduced in 2014), you can only request birthdays of friends that pass the following criteria:
  - They have installed your application
  - Their birthday privacy is set to the scope that is visible to you

I would suggest using our [Graph API Explorer](https://developers.facebook.com/tools/explorer/145634995501895?method=GET&path=me%2Ffriends%3Ffields%3Dbirthday&version=v2.8) tool and set it to your app, to play with the API faster and look into what you can and cannot retrieve via Graph API.

Let me know if you have any questions.
