### ISSUE TITLE
xcodebuild timed out while trying to read FacebookSwift.xcworkspace

### ISSUE THREAD

**Issue by SimonRiis** [facebook/facebook-sdk-swift#78]
Hi 

I am trying to get up and running using carthage. 
Bolt is being built just fine, but not the FacebookSDK... I keep getting this error: xcodebuild timed out while trying to read FacebookSwift.xcworkspace

$ carthage update
**\* Fetching Facebook-SDK-Swift
**\* Fetching facebook-ios-sdk
**\* Fetching Bolts-ObjC
**\* Checking out Bolts-ObjC at "1.8.4"
**\* Downloading facebook-ios-sdk.framework binary at "4.16.1"
**\* Checking out facebook-ios-sdk at "sdk-version-4.16.1"
**\* Checking out Facebook-SDK-Swift at "0.2.0"
**\* xcodebuild output can be found in /var/folders/6v/lqj_5ph13sxdl529hss287l80000gn/T/carthage-xcodebuild.mE1vzx.log
**\* Building scheme "Bolts-macOS" in Bolts.xcodeproj
**\* Building scheme "Bolts-tvOS-Dynamic" in Bolts.xcodeproj
**\* Building scheme "Bolts-watchOS-Dynamic" in Bolts.xcodeproj
**\* Building scheme "Bolts-iOS-Dynamic" in Bolts.xcodeproj
**\* Building scheme "FBSDKCoreKit_TV-Dynamic" in FacebookSDK.xcworkspace
xcodebuild timed out while trying to read FacebookSwift.xcworkspace

**Comment by SokichiFujita** [comment]
I also have similar issue with Carthage v0.18.

```
carthage update --platform iOS
*** Fetching facebook-sdk-swift
*** Fetching facebook-ios-sdk
*** Fetching Bolts-ObjC
*** Checking out Bolts-ObjC at "1.8.4"
*** Downloading facebook-ios-sdk.framework binary at "4.18.0"
*** Checking out facebook-ios-sdk at "sdk-version-4.18.0"
*** Checking out facebook-sdk-swift at "0.2.0"
*** xcodebuild output can be found in /var/folders/1h/s15nx04s6p70y55377wnf7wh0000gn/T/carthage-xcodebuild.BwMl4A.log
*** Building scheme "Bolts-iOS-Dynamic" in Bolts.xcodeproj
xcodebuild timed out while trying to read FacebookSDK.xcworkspace
```

**Comment by Fjohn666** [comment]
Same here ... any idea to resolve that ?

**Comment by spandanabatchu** [comment]
Same with running `carthage update --platform iOS --no-use-binaries` on Xcode9beta6
