### ISSUE TITLE
How long will this sdk be in beta stage?

### ISSUE THREAD

**Issue by kiwo12345** [facebook/facebook-sdk-swift#81]

**Comment by nlutsenko** [comment]
Hey @kiwo12345, that's a very good question.
The best answer that I have for you is: until the moment we are comfortable locking down the APIs and are confident that the SDK is production level quality.

The `beta` label, doesn't mean that the SDK is not usable in the applications. 
At the current stage, it mostly ensures that everyone is aware that there might be drastic changes coming to the API and be ready for it.
