### ISSUE TITLE
Graph Request is return succesValue only

### ISSUE THREAD

**Issue by bkrijgsman** [facebook/facebook-sdk-swift#85]
Hi,

I'm creating a Graph Request, but only receive the succes value in the result.

Code i'm using:

`let req = GraphRequest(graphPath: "me", parameters: ["fields": "id, name"], accessToken: token, httpMethod: .POST, apiVersion: .defaultVersion)

```
            _ = req.start { (httpResponse, result) in

                switch result {
                case .success(let response):
                    print(result)
                    print(httpResponse)                    

                case .failed(let error):
                    print("Graph Request Failed: \(error)")
                }

            }`
```

The result is showing:

> success(FacebookCore.GraphResponse(rawResponse: Optional({
>     success = 1;
> })))

If i call the URL manually in my browser (which comes from the HTTPResponse) i get a valid result.

I'm using Swift 3.0
FacebookShare (0.2.0):
    - Bolts (~> 1.8)
    - FacebookCore (~> 0.2)
    - FBSDKCoreKit (~> 4.15)
    - FBSDKShareKit (~> 4.15)

**Comment by nlutsenko** [comment]
Hey @bkrijgsman,

Looks like you are using `.POST`, which is a mutation method for `me`, not receiving one.
Adjust your request to the following to receive the proper info:
```
let req = GraphRequest(graphPath: "me", parameters: ["fields": "id, name"], accessToken: token, httpMethod: .GET, apiVersion: .defaultVersion)
```

Also, our [Graph API Explorer](https://developers.facebook.com/tools/explorer/145634995501895/?method=POST&path=me%3Ffields%3Did%2Cname&version=v2.8) is a very helpful tool to see what the response will looks like on success for both POST and GET methods.

**Comment by bkrijgsman** [comment]
@nlutsenko thank you very much, this was a bit stupid. I tried the Graph API Explorer, but didn't saw that I was using a POST request (a)
