### ISSUE TITLE
Module compiled with Swift 3.0 cannot be imported in Swift 3.0.1

### ISSUE THREAD

**Issue by hallelujahbaby** [facebook/facebook-sdk-swift#86]
I got this error with Xcode 8.1 GM

Full Log:

/Users/xxxxxx/xx/xxxx/Login/LoginVC.swift:10:8: Module compiled with Swift 3.0 cannot be imported in Swift 3.0.1: /Users/xxxxxxxx/xxxxx/Carthage/Build/iOS/FacebookCore.framework/Modules/FacebookCore.swiftmodule/x86_64.swiftmodule

Does anyone have any solution ? Thanks a lot.

**Comment by hallelujahbaby** [comment]
Problem solved, after rebuilt with XCode 8.1 Public Release.

**Comment by kiroskirin** [comment]
@hallelujahbaby 
I'm facing the same.
How can I rebuild with Xcode? 
PS. Sorry I'm new with FB SDK

**Comment by hallelujahbaby** [comment]
I am using Carthage as dependency tool.

I just install the latest Xcode, and run 
"carthage install" in terminal, carthage will help you to rebuild it.
