### ISSUE TITLE
canShare boolean and ShareError

### ISSUE THREAD

**Issue by rudedogg** [facebook/facebook-sdk-swift#89]
In `ShareError.swift` it mentions a boolean property to check whether Sharing is available. Is this available through the Swift SDK? I tried searching but could only find it in the Objective-C SDK.

Also, I don't think `ShareError.dialogNotAvailable` is being thrown. I tried catching it, but instead `ShareError.reserved` is thrown when running on the simulator.

ShareError.swift comment mentioned above:
```swift
  /**
   The error code for when a sharing dialog is not available.
   Use the `canShare` property to check for this case before calling show.
   */
  case dialogNotAvailable
```

**Comment by nlutsenko** [comment]
Hey @rudedogg, that's a nice catch.
The proper function name that this refers to is `validate()`, for example [here](https://github.com/facebook/facebook-sdk-swift/blob/master/Sources/Share/Dialogs/ShareDialog/ShareDialog.swift#L104).
This ensures that you are using the dialog with the appropriate content type and that all of the required fields are present and pass the basic validation.

If you provide more source code/context, most importantly - something I can use to reproduce the problem, that would let me help you 😁
