### ISSUE TITLE
Get ReadPermission from Permission

### ISSUE THREAD

**Issue by nico75005** [facebook/facebook-sdk-swift#91]
When I log in, I give a list of permissions (`ReadPermission`).
If the user doesn't allow one permission, I want to explain him why I need it and offer him a way to change his mind by asking for the missing permission again.

The problem is that the declined permissions are a set of `Permission` and the name of the permission in `internal` and I cannot create a `ReadPermission` from `Permission` as I cannot reach the underlying `String`. 

Is there a way to make this happen?

**Comment by nlutsenko** [comment]
Hey @nico75005,

Thanks for the feedback.
This is a great use case and we absolutely should publicize the `name` property of the permission.
Let me mark this as enhancement and send a pull request in a short while to improve this.
