### ISSUE TITLE
Hitting 'reserved' error when using 'VideoShareContent'

### ISSUE THREAD

**Issue by edgeofchaos2005** [facebook/facebook-sdk-swift#93]
I've copied the sample files code to share a locally stored video, but every time I pass a videoURL in, I receive an error of 'reserved', does the video need to be remote?

I'm using Swift 3 and Xcode 8.0.

        func fbClicked(sender: UIButton?) {
        
            let video = Video(url: videoURL)
            let content = VideoShareContent(video: LOCAL_VIDEO_URL)
        
            self.showShareDialog(content, mode: .automatic)
        }
        
        func showShareDialog<C: ContentProtocol>(_ content: C, mode: ShareDialogMode = .automatic) {
            let dialog = ShareDialog(content: content)
            dialog.presentingViewController = self
            dialog.mode = mode
            do {
                 try dialog.show()
            } catch (let error) {
                 print(error)
            }
        }

**Comment by edgeofchaos2005** [comment]
Can't share a locally stored video, have to share a video from the asset lib, so the UIImagePickerController, then choose a video.

**Comment by manonthemoon42** [comment]
@edgeofchaos2005 , were you able to use the Share Dialog?
I'm trying to use it with a valid video URL (not local), and I'm still getting the error `reserved`. Pretty confusing,
