### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by Rigelnetworks** [facebook/facebook-sdk-swift#94]
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1.

i installed in my project directory

touch podfile
 touch Podfile
open -e Podfile
 pod install..

but but gives me error.

**Comment by nlutsenko** [comment]
Hey @Rigelnetworks,

Unfortunately without more information, there is not really a way I can help you.
Could you attach your project or link to this report that showcases the problem?
Also, specifying the exact error that you are experiencing would help a lot.

Please note, that this is a single report of this sort, so I bet there is something specific about your project/structure/build environment that causes this error.

**Comment by Rigelnetworks** [comment]
Thank you for replying but that issue was solved. And my question is that how can I fetch user's email ID,phone number,friends list, friend's email_id, friend's phone number in my app?

**Comment by Drwalcore** [comment]
@Rigelnetworks You really should mention **HOW** you solved that issue :/
