### ISSUE TITLE
Support for Swift 3.0.1

### ISSUE THREAD

**Issue by EdmundoRodrigues** [facebook/facebook-sdk-swift#98]
Added the pods for Swift SDK, however Xcode 8.1 wants to convert the frameworks to latest version of Swift. 

Any idea when an updated framework will be available?

**Comment by nlutsenko** [comment]
Current master should work no problem with Xcode 8.1 and Swift 3.0.1.
Will cut the release soon, stay tuned.

**Comment by SAPIENTechnologies** [comment]
Was wondering when we can expect the update to Swift 3?

**Comment by Fritiof** [comment]
Same here, not working with 3.0.1

**Comment by christinalau** [comment]
I am also having this issue on XCode 8.1 (8B62). Is there a workaround? I get the following error message and even if I set to "yes" in Use Legagacy, I still cannot get a clean build.

“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
