### ISSUE TITLE
Issue 37 is not available in release 0.2.0

### ISSUE THREAD

**Issue by garrefa** [facebook/facebook-sdk-swift#99]
The changelog for release 0.2.0 says:
- Add iOS 9.0+ method for opening URLs to ApplicationDelegate. #37 (nlutsenko)

But when i install 0.2.0 (at least with cocoapods) i dont see the change applied.
Instead, i still have the old method where options is of kind `[UIApplicationOpenURLOptionsKey : Any]`

```swift
  @available(iOS 9.0, *)
  @discardableResult
  public func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any] = [:]) -> Bool {
    return delegate.application(app,
                                open: url,
                                sourceApplication: options[UIApplicationOpenURLOptionsKey.sourceApplication] as? String,
                                annotation: options[UIApplicationOpenURLOptionsKey.annotation])
  }
```

[issue 37 link](https://github.com/facebook/facebook-sdk-swift/pull/37)

Just found out that this [commit](https://github.com/facebook/facebook-sdk-swift/commit/2539f599b2e9310e3e7192674a801bee2cb435b4) undid the change.

My [PR](https://github.com/facebook/facebook-sdk-swift/pull/100) to fix this

**Comment by nlutsenko** [comment]
Looks like this is not an issue, per discussion in #100.
